### ISSUE TITLE
[Proposal] Communications Working Group

### ISSUE THREAD

**Issue by caradelia** [cncf/tag-env-sustainability#107]
#### Description
Create separate working group (WG) focused on communications for the TAG to organize communications and marketing efforts.

#### Impact
This WG will help to focus our main meetings. Each main meeting will include an update from Comms WG.

#### Scope
Separate meetings (to be determined frequency/length by TAG) from main meeting regarding the following:

- events
- website maintenance
- marketing
- content (blogs, white papers, website copy, etc.)

...

**Comment by leonardpahlke** [comment]
cc @catblade @mkorbi

**Comment by TheFoxAtWork** [comment]
LGTM, @erinaboyd & @mattfarina ?

**Comment by catblade** [comment]
All for this.

**Comment by leonardpahlke** [comment]
+1

**Comment by erinaboyd** [comment]
LGTM

**Comment by asiwaju001** [comment]
+1

**Comment by guidemetothemoon** [comment]
I think that this is a great idea! +1 from me as well.

**Comment by mkorbi** [comment]
mere formality +1 ;)

**Comment by caradelia** [comment]
Proposal for the Comms Working group charter found in this new issue:
https://github.com/cncf/tag-env-sustainability/issues/206

**Comment by caradelia** [comment]
Proposal for the Comms Working group charter found in this new issue:
https://github.com/cncf/tag-env-sustainability/issues/206
