### ISSUE TITLE
[Action] Landscape Document Versioning

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#115]
The [TAG ENV landscape document](https://tag-env-sustainability.cncf.io/about/landscape/) has been published earlier this year as a v0.1 release. We know that its not complete, that we have gaps and that we need to fill those over time. At the moment the version is highlighted in the markdown file at the top of the document.

### Problem

When we add something to the document, there is no direct way to go back to previous versions. We lose track of versions and only ever see the latest version.

TAG chairs and ToC liaisons need to sign off on a version. It is not desirable to sign off on every small change to the documentation. Since we have introduced versioning in the document, which makes sense, we should take this into account and make older versions easy to find. 

### Resolution Proposal

1. We add versioning to the document. Docsy (the website template) has document versioning. See https://www.docsy.dev/docs/adding-content/versioning/ - it looks like we manage versions via different branches.
2. You may argue that its not a problem to see just the latest version. We could upload a PDF with every landscape release for those few folks that refer to a specific version.

I like 2. for the simplicity reasons. 

cc @catblade

**Comment by catblade** [comment]
I am with (2).  We can version yearly, or every 6 months?  I know our versioning is currently 0.x, but maybe we can go
23.06 (if we were versioning today) and then move forward from there.

**Comment by leonardpahlke** [comment]
> We can version yearly, or every 6 months

Maybe at least once a year, and if there is a need, we can do it more often. I like the idea of releasing a new version before each KCCN xor OSS summit, when there is of course something to release.

>  I know our versioning is currently 0.x, but maybe we can go
23.06 (if we were versioning today) and then move forward from there.

Good idea. I think that makes sense. Lets rename the versions.

**Comment by mkorbi** [comment]
Would prefer a timestamp like proposed by Marlow rather than a version.

**Comment by catblade** [comment]
Above the example (23.06) is for yy&month.  Do you think we need day?  We can add a .1 if we have to, but I don't see this being released or updated more than once a month.

**Comment by guidemetothemoon** [comment]
Fair point. Considering release frequency there's no need to include day. Adding .1 is a good alternative in case multiple releases happened on the same month, which will be less likely.

**Comment by catblade** [comment]
Commit is in.  Anyone mind if I close this out?

**Comment by guidemetothemoon** [comment]
OK from me to close it 😊
