### ISSUE TITLE
Define branch protection rule for `main`

### ISSUE THREAD

**Issue by chalin** [cncf/tag-env-sustainability#122]
GH warning regarding `main`:

> <img width="696" alt="Screen Shot 2023-06-14 at 10 41 55" src="https://github.com/cncf/tag-env-sustainability/assets/4140793/d47cfbf7-80c1-40d1-ba2f-e793d4b0e738">

We should create a branch protection rule if only to prevent force-pushes and deletions.

I can make the rule addition once given the appropriate green light to do so.

/cc @nate-double-u @cjyabraham

**Comment by nate-double-u** [comment]
+1

**Comment by leonardpahlke** [comment]
+1, thanks

**Comment by nate-double-u** [comment]
I can make the update. Do we want to require a specific number of approvals for PRs?

**Comment by chalin** [comment]
I'd vote to only create a default protection rule for now -- which will protect from force-pushes and deletions. Other parameters can be tweaked later.

**Comment by nate-double-u** [comment]
OK, I've created it as follows:
<img width="783" alt="Screenshot 2023-06-14 at 8 46 49 AM" src="https://github.com/cncf/tag-env-sustainability/assets/4453979/e1b73164-1ef8-4f4c-b7ff-e11ce0a3e449">

We can update as needed.
