### ISSUE TITLE
[Action, Cloud Native Sustainability Week] Welcome Slides

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#126]
Part of #95 

Each local meetup will talk about the Cloud Native Sustainability Week at the beginning during their meetup. To help local meeting organizers with this task, we could create a presentation that can be used at each local meeting to introduce the event, CNCF, and TAG ENV.

Slides: https://docs.google.com/presentation/d/1QPWMflUsaNeD1iEHBt4Y0be5H9JO3wwkEFoimVXcAhk/edit?usp=sharing

**Comment by Nancy-Chauhan** [comment]
I am interested

**Comment by mehmetmgrsl** [comment]
me too :)

**Comment by leonardpahlke** [comment]
cc @AntonioDiTuri

**Comment by leonardpahlke** [comment]
We can reach out to the CNCF to help us create a presentation template design. I can do that. @Nancy-Chauhan @mehmetmgrsl @AntonioDiTuri how do you envision the design? So, the designer has some guidance.

About the content on the slides. I think for now, we can use the link I shared above and as soon as the template is created we can copy the content over. 

Ad-hoc Slides:
1. Title slide: CNCF Cloud Native Sustainability Week & TAG, CNCF logo
2. Info about the event: Event abstract text
3. Info about the local meetup location: A world map with pins in all the locations.
4. Info about the TAG ENV
5. Info about the cloud native sustainability landscape: maybe a diagram (see https://drive.google.com/file/d/1mAyezTMtGsBqHEElYReoPWpyc82bgQLq/view?usp=share_link) 
6. Slide how to contribute to the TAG ENV (list of projects, wg, and upcoming topics…)

Feel free to change this ^

Thanks all!

**Comment by mehmetmgrsl** [comment]
> * Title slide: CNCF Cloud Native Sustainability Week & TAG, CNCF logo
> * Info about the event: Event abstract text
> * Info about the local meetup location: A world map with pins in all the locations.
> * Info about the TAG ENV
> * Info about the cloud native sustainability landscape: maybe a diagram (see https://drive.google.com/file/d/1mAyezTMtGsBqHEElYReoPWpyc82bgQLq/view?usp=share_link)
> * Slide how to contribute to the TAG ENV (list of projects, wg, and upcoming topics…)

Thanks for the ad-hoc slides suggestion @leonardpahlke . They are LGTM :)

I would like to add a few more points about slides:

- visually appealing : Instead of paragraphs , some infographics can be used)

- event hashtag can be added (maybe in the 'info about the event' slide)

- Social Media Wall: During the event where attendees' posts and tweets are displayed in real-time.

- Feedback and Surveys:  A link to the survey that will be created as a result of the study (https://github.com/cncf/tag-env-sustainability/issues/128)

**Comment by leonardpahlke** [comment]
@mehmetmgrsl great ideas!!

@mehmetmgrsl could you comment this idea `Social Media Wall: During the event where attendees' posts and tweets are displayed in real-time.` and `event hashtag can be added (maybe in the 'info about the event' slide)` to this issue #130
