### ISSUE TITLE
[Action, Cloud Native Sustainability Week] Survey for local meetup organizers

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#127]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

To learn from experiences, discussions, and input made in local meetups, we will share a survey across local meetup organizers after the event happened to give in more detail feedback on their event. The goals of the event are mentioned in this [doc](https://docs.google.com/document/d/1s28lqqc3IBAMw4T7n13zfyAuUEEc3I4_xhPxCLA4_dk/edit).

Survey: https://docs.google.com/forms/d/1xtj9XzqTpNA1ZB8dhX8L_N_LXkdJfrIZvU2jiKsXTJ4/edit?pli=1

**Comment by mehmetmgrsl** [comment]
I am interested

**Comment by leonardpahlke** [comment]
LF Research updated the survey on a copy here: https://docs.google.com/forms/d/1mLyGBnpGSxmmvf656THKIHjbvMs2fE7LG3k8Be6M5Ek/edit @mehmetmgrsl can we update our version? Thanks!


> changed one question from single response options to a scale of 1 to 5
