### ISSUE TITLE
[Action, Cloud Native Sustainability Week] Attendee Survey

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#128]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

With so many events happening across the globe, it's a great time to share a survey with attendees. The survey should be easy to submit, not long to fill out but giving the option to go into more detail (optional). The details have yet to be discussed.

Survey: https://docs.google.com/forms/d/1I-TBVKsKZnn_VxpiYyo5Vl7KIy8NYV1MVj31YmR08HU/edit

**Comment by mehmetmgrsl** [comment]
me too

**Comment by catblade** [comment]
Would add to the survey something around "Did you identify any organizations or projects you intend to engage with within the next 6 months?" with a follow-up of asking which ones.

**Comment by ramrodo** [comment]
I would add numbers to each question to give/receive feedback from here easier.

- I would mark all questions as Mandatory except for questions:
  - "Which cloud native sustainability practices do you already follow in your projects"
  - "Challenges implementing environmental sustainability cloud native practices into your projects"
  - "What suggestions do you have for improving future editions of the CNCF Global Week of Cloud Native Sustainability meetups?"
  
Everything else looks great!

**Comment by leonardpahlke** [comment]
Awesome, feel free all to update the survey. 

Unfortunately, the Google Forms does not have a suggestion feature… Maybe in the future we can design the survey on Google Docs first…

We can go through the survey in two weeks and then send it to LF Research, so they can take a look over the questions etc.

**Comment by leonardpahlke** [comment]
LF Research upadated the survey on a copy here: https://docs.google.com/forms/d/1SCfeUNpXs9CwLlPdJpc4c2Iw6PszpPffrq7LUqxPYrA/edit @mehmetmgrsl can we update our version? Thanks!

**Comment by mehmetmgrsl** [comment]
> LF Research upadated the survey on a copy here: https://docs.google.com/forms/d/1SCfeUNpXs9CwLlPdJpc4c2Iw6PszpPffrq7LUqxPYrA/edit @mehmetmgrsl can we update our version? Thanks!
> 
> > But important - in some questions single option answer was coded where multi-response (check box) answer is required, some clarifying language on the scale questions, and so on.

Hey @leonardpahlke ,

The updated version already includes my question which is "Which of the following poses the greatest challenge to implementing environmental sustainability cloud native practices into your projects? Select one. ?"

Do I need to do anything else?

**Comment by leonardpahlke** [comment]
I have made a few adjustments to the survey: https://forms.gle/UJVkRT6uJZ2F7TG67 

cc @guidemetothemoon @Nancy-Chauhan

**Comment by leonardpahlke** [comment]
survey edit link: https://docs.google.com/forms/d/1I-TBVKsKZnn_VxpiYyo5Vl7KIy8NYV1MVj31YmR08HU/edit
