### ISSUE TITLE
[Action, Cloud Native Sustainability Week] Credly Badges

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#129]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

To recognize local meetup organizers, it would be great to issue Credly badges after the event. We could also potentially give out badges to speakers who give talks on Cloud Native Sustainability. First we need to reach out to CNCF to create Credly badges for these efforts and go from there. 

Any designs that may be created can be uploaded here: https://drive.google.com/drive/folders/1JUtrZr-Aajv7j7gJtA4NC04eYxEydRqR?ths=true

**Comment by guidemetothemoon** [comment]
I can help out here :)

**Comment by leonardpahlke** [comment]
@k8tgreenley do you may know whom to contact at the LF about credly badges? I assume we need to bring a design to visualize the badge. May you know the requirements of the image (size, etc.). Are there any other documents we need to provide? I guess after the event happened a list of names / emails - anything else? Thanks!

**Comment by sysnet4admin** [comment]
@leonardpahlke 
Cloud it the sample of `Credly Badges` ?
(i.e. 2 type of contributions?)
I just would like to check or sync up your thought. 

**Program Committee** 
![image](https://github.com/cncf/tag-env-sustainability/assets/29163931/c1855927-8547-4f87-be4e-533f5b0441d9)

**Speaker**
![image](https://github.com/cncf/tag-env-sustainability/assets/29163931/235d7828-de6c-4115-a047-af04654dd0dc)

**Comment by leonardpahlke** [comment]
Thanks @sysnet4admin :) right, we are planning to issue badges to organizers, local meetup organizers and potentially also speakers. I think badges are a great way to acknowledge the work we all put in. They are usually well received :)

Regarding the design, thanks! We can be flexible with the design of the badges. Last week @Bamistand proposed to work on a design 🙌

**Comment by Bamistand** [comment]
@leonardpahlke I made adjustments to the designs as we discussed yesterday, and I have uploaded them on the drive, which is of course still open to further adjustment if needed.

**Comment by leonardpahlke** [comment]
Thanks Mercy! I will reach out to the CNCF to check if the design is from a legal point of view ok. Thanks!

**Comment by leonardpahlke** [comment]
@Bamistand could we replace the CNCF logo with the TAG ENV logo - that way, everyone’s aware of which group it is? Thanks! https://github.com/cncf/artwork/tree/master/other/tag-environmental-sustainability

**Comment by Bamistand** [comment]
@leonardpahlke Yes, we can do that. It will be worked on.

**Comment by seokho-son** [comment]
Hi @leonardpahlke 

I'm reaching out to inquire about the current status of badge preparations for the meetup.

To clarify, we're planning to issue badges to organizers of the Cloud Native Sustainability Week meetups as well as to the speakers, correct? Is there a possibility to extend this to contributors as well, such as student volunteers?

Has the design of the badges been confirmed by CNCF? (I have experience in badge design and received confirmation for the KCD Korea badge, so if needed, I'm available to assist with any required procedures.)

Is it permissible for meetups to announce that the LF will be issuing these badges to organizers and speakers?

Thank you. :)

**Comment by leonardpahlke** [comment]
@Bamistand could you upload this badge version https://drive.google.com/file/d/15bnXvMO7rV9SHcmKS7ZtZVgAzlPGW-c-/view?usp=share_link with the text "Speaker" instead of "Meetup Organizer" so we have both ready to go 🙌 
Thanks Mercy!

**Comment by Bamistand** [comment]
@leonardpahlke I have added a copy https://drive.google.com/file/d/1BTmuioY2PetMwJs0Uh4aKZ4CXKFgZBUk/view?usp=sharing for Speaker.

**Comment by guidemetothemoon** [comment]
Have we sent out all the organizer/speaker Credly badges? If so, I may be missing the speaker one from Oslo meetup 😇

**Comment by leonardpahlke** [comment]
Yes, we send out all the badges. There was a limit of maximum badges, so we issued just once per person.
