### ISSUE TITLE
Set up a project board to plan working group initiatives 

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#13]
_Issue mentioned in the agenda of the first charter meeting 1 June_ 

Tasks:
- [x] Discuss the need of a project board (WG Meeting 1 June)
- [x] Agree on a tool to host the project board (like: GitHub / Jira / ...)  (WG Meeting 1 June)
- [x] Create and configure the project board
- [ ] Give write access to charter members

cc @rootfs

**Comment by leonardpahlke** [comment]
@mkorbi, do you have the access rights to create a GitHub Project board?

**Comment by jeefy** [comment]
Created https://github.com/orgs/cncf/projects/10/ but for some reason I cannot invite @leonardpahlke onto it. :\ Will investigate later.

**Comment by leonardpahlke** [comment]
Thank you :)

**Comment by catblade** [comment]
Is it possible for others in the community to add to the board?  We have agreement on beginning a landscape/use case whiteboard to document all the current known technologies within this space and what users may want to use them.

**Comment by mkorbi** [comment]
Project Board 
https://github.com/orgs/cncf/projects/10/views/1
