### ISSUE TITLE
[Tracking, Cloud Native Sustainability Week] Social Media Promotion

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#130]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

The CNCF is supporting us in promoting the event over their social media platforms. To support the local meetup organizers and the event overall, we should leverage this platform and coordinate announcements. First, we should sync with the CNCF (pr@cncf.io) about this event and create a lightweight social media plan.

This document can be used for planning: https://docs.google.com/document/d/1jfv5yPABd6unFrRcPqTV-SkFo5z1qhnkm3Zd1JeJmKg/edit#heading=h.73pgf6pbinj0

**Comment by Nancy-Chauhan** [comment]
Hey @leonardpahlke What would be the timeline here ?

**Comment by leonardpahlke** [comment]
We have a bit of time here. I think we should contact the CNCF PR team soon. Maybe there is more work, which we don't see right now.

**Comment by leonardpahlke** [comment]
@Nancy-Chauhan if you have time, I would appreciate it if you could reach out to pr@cncf.io and make them aware of this event + ask how to sync on the social media promotion. & put me cc (leonard.pahlke@googlemail.com) Thanks!

**Comment by mehmetmgrsl** [comment]
Hi,
I would like to add a suggestion below:

Social Media Wall: During the event where attendees' posts and tweets/threads are displayed in real-time.

**Comment by leonardpahlke** [comment]
LinkedIn & Twitter post templates: https://docs.google.com/document/d/1dOfCuHDc3oi1-WmnbkUpmv6Asev4yLFiharzhwrjFCA/edit

**Comment by leonardpahlke** [comment]
we can use the `#CloudNativeSustainabilityWeek` posting announcements etc.

**Comment by pichuang** [comment]
We already publish the event in Taiwan. Thanks for the team's help.

Facebook Group Post: https://www.facebook.com/groups/cloudnative.tw/posts/1691459571357371/
Community Event Page: https://community.cncf.io/events/details/cncf-cloud-native-taiwan-user-group-presents-cncf-sustainability-week-taiwan-x-green-software-foundation/

**Comment by guidemetothemoon** [comment]
FYI, content plan for the next weeks is outlined in the following Google Doc and will be populated continuously: https://docs.google.com/document/d/1Tqzzfz4YdnbYLumqcniJhF4Anm7OTxiXwyBdL6IpTwk/edit
If you have any suggestions, please reach out!☺️
