### ISSUE TITLE
[Tracking, Cloud Native Sustainability Week] TAG ENV Virtual Meetup

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#131]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

Part of the cloud native sustainability week is a virtual meetup by the TAG ENV to discuss the group's goals, vision, projects, members, and host external talks.

We can use bevy to host the virtual event. The CNCF has an account and can create a page for us (@k8tgreenley).

Ad-hoc upcoming action items:
1. Setup environment to host the meetup virtually using bevy
2. Define an agenda and schedule
3. Define CFP guidelines 
4. Announce the virtual event and call for speakers
5. Select & Invite speakers
6. Create resources such as slides, videos etc. (see #126, see [getting started slides](https://drive.google.com/file/d/1mAyezTMtGsBqHEElYReoPWpyc82bgQLq/view?usp=sharing), + some new slides)
7. Promote the virtual event (see #130)
8. Hold the virtual meetup.

Artifacts like presentations, documents etc. can be uploaded to this folder: https://drive.google.com/drive/folders/1xpaArKURUraPpYdtSeeEQrB1ri6gxI0a?ths=true

**Comment by k8tgreenley** [comment]
@leonardpahlke let me know when the page needs to be created

**Comment by Nancy-Chauhan** [comment]
I would love to help with this

**Comment by guidemetothemoon** [comment]
I can help out as well :)

**Comment by Bamistand** [comment]
I am interested too

**Comment by guidemetothemoon** [comment]
I will create a simple Google Form for CFP submission and add it to the above folder.

**Comment by catblade** [comment]
You'll need a review committee too.  We might reach out to the OSS on their sustainability con piece and see if they have any good suggestions.

**Comment by leonardpahlke** [comment]
Yes, that's important, but we should keep it simple.

**Comment by leonardpahlke** [comment]
@k8tgreenley could we create the virtual group, so we can get used to the platform and start planning the event? Thanks!

**Comment by leonardpahlke** [comment]
Yes, good idea +1, we can add this to the form.

**Comment by guidemetothemoon** [comment]
Thanks for the feedback! Added two additional questions on session duration and benefits to the cloud native ecosystem.

**Comment by Nancy-Chauhan** [comment]
I am working on having a Community page at https://community.cncf.io/

**Comment by leonardpahlke** [comment]
Thanks Nancy 🙌

**Comment by leonardpahlke** [comment]
We discussed in today's cloud native sustainability week meeting using the CFP form as well for local meetup organizer sign up (as an option).

**Comment by guidemetothemoon** [comment]
We discussed a bit further with @leonardpahlke and would like to publish the CFP form next week.

I did additional updates to the form:
- Added a drop-down list where a speaker can choose whether they would like to present at a virtual meetup or any of the confirmed local meetups. Entries for the local meetups will be shared with the respective organizers, and this is meant as an additional way to submit speaker interest for a local meetup. As a local meetup organizer you can still use a dedicated CFP page if you'd like. Updated the CFP form to be more generic and account for this change since it's not only targeted at the virtual meetup anymore. Shared this information in the Slack channel and related GitHub issue #134 
- Added a very simple banner to make the form look more appealing.

If you have any comments/suggestions, please share them here or in the Slack channel **before next planning meeting for the event which is on Thursday, 17th of August** 😊

**Comment by k8tgreenley** [comment]
@Nancy-Chauhan did you submit a request for the meetup page?

**Comment by Nancy-Chauhan** [comment]
> @Nancy-Chauhan, did you submit a request for the meetup page?

Hey @k8tgreenley, Can you please help me with it? I did send a request in the Slack channel. Do you think I should also be raising the request somewhere else?

**Comment by leonardpahlke** [comment]
Thanks @Nancy-Chauhan :)

**Comment by guidemetothemoon** [comment]
CFP for Cloud Native Sustainability Week virtual meetup and local meetups is now open!🥳

This link can be shared with others: https://docs.google.com/forms/d/e/1FAIpQLSdwy7gaIbgyfITJhDC1axzR9AuO6rPuZGyi2nZQynILgP77qQ/viewform?usp=sf_link

As mentioned earlier submissions to local meetups will be shared with respective local meetup oranizers and will be aggregated in this document: https://docs.google.com/spreadsheets/d/1i7UcKr9Fz1QYqCawrjBwWDpTsUZ1HQRFNWSVRAvQcCE/edit?usp=sharing

We have published announcement both on our LinkedIn page (give it a follow😊) and Twitter/X - please spread the love!
LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7100112838999875584
Twitter/X: https://twitter.com/CNCFEnvTAG/status/1694348695045603790?s=20

Thank you!😊

**Comment by leonardpahlke** [comment]
@Nancy-Chauhan @Bamistand do you may have a bit of time this week to work on an agenda for the virtual cloud native sustainability meetup? 🙏 

blank doc: https://docs.google.com/document/d/1JaB1frApyxSc_GBUYMyXihC3GW_un0lQ_qgJMwhxdHM/edit?usp=sharing

**Comment by Nancy-Chauhan** [comment]
Hey, @leonardpahlke Sure! Can you please give me a brief here? What are we looking for? Are we supposed to work on an agenda that will later go over the virutal meetup community page

**Comment by leonardpahlke** [comment]
Right, we are looking for an agenda for the virtual tag env meeting. We will have an introduction session, talking about the TAG ENV, and two talks or so. Maybe something to end the event to close it. Maybe we can have a slot in the beginning or the end for WG comms and WG Green Reviews and a slot talking about the landscape. I would plan around 2h for the event.

**Comment by leonardpahlke** [comment]
Thanks Nancy! 🙌

**Comment by Nancy-Chauhan** [comment]
Thanks Leo. Working on doc 🚀

**Comment by Nancy-Chauhan** [comment]
Hey @leonardpahlke Can you please review the doc

**Comment by guidemetothemoon** [comment]
It's so nice to put some structure into the virtual meetup plan - thanks for doing it, @Nancy-Chauhan !😊
Added two small comments from my side.
