### ISSUE TITLE
[Action, Cloud Native Sustainability Week] Website Page

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#132]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

To share the details about the event, it would be great to have a website page. We can either be utilizing the [TAG ENV website](https://tag-env-sustainability.cncf.io/) or create a page on [cloudnative-sustainability.com](https://cloudnative-sustainability.com/).

We can upload any resources / create documents in this folder: https://drive.google.com/drive/folders/1w5rjLsBZiUOgyYMhSlT7e-lB-UG4VItO?ths=true

**Comment by guidemetothemoon** [comment]
I can help out :)

**Comment by leonardpahlke** [comment]
Opened a PR, see https://github.com/cncf/tag-env-sustainability/pull/142

**Comment by Azanul** [comment]
I see a merged PR but an open issue

**Comment by leonardpahlke** [comment]
Right, we can close this one. I kept it open if there is more input to add to the website. I think we are good, no need to track it.
