### ISSUE TITLE
[Presentation] Falco and TAG Environmental Sustainability Partnership

### ISSUE THREAD

**Issue by incertum** [cncf/tag-env-sustainability#140]
#### Title

Falco and TAG Environmental Sustainability Partnership

...

#### Speaker

Melissa Kilby (@incertum) - Falco Core Maintainer
...

#### Description

Discuss options available
- (1) to provide adopters with a self-service option for making informed decisions on configuring and tuning security monitoring in their unique environment -> measure the impact of Falco's resource utilization and ensure transparency in its utilization for production environments.
- (2) for tracking Falco's resource utilization between release by leveraging a formal testing infrastructure.

https://github.com/falcosecurity/falco/issues/2435.
https://falco.org/
...

### Time

15 min total (presentation only 5 min)

...

### Availability

July 19th - 8am PST

...

### Steps
1. [x] First, contact one of [TAG ENV
   Co-Chairs](https://github.com/cncf/tag-env-sustainability#tag-environmental-sustainability-co-chairs) or [TLs](https://github.com/cncf/tag-env-sustainability#tag-environmental-sustainability-tech-leads) to confirm your presentation. You can tag them in this GitHub issue or contact them through the [CNCF Slack](https://communityinviter.com/apps/cloud-native/cncf) channel [#tag-environmental-sustainability](https://cloud-native.slack.com/archives/C03F270PDU6).
2. [x] Then, add the topic to the Agenda of the upcoming regular meeting in the
   [meeting notes](https://docs.google.com/document/d/1TkmMyXJABC66NfYmivnh7z8Y_vpq9f9foaOuDVQS_Lo/edit).
   Format: `[NAME] Presentation: "<title of your presentation>" <link to this issue>`
3. [x] Post a message in the [CNCF Slack](https://communityinviter.com/apps/cloud-native/cncf) channel [#tag-environmental-sustainability](https://cloud-native.slack.com/archives/C03F270PDU6) to inform other TAG ENV members so that they can join!

We are already engaged in a formal discussion

**Comment by catblade** [comment]
Added to the meeting notes.  I'll put @incertum  as the presenter when we tweet a week ahead, and then with the slack channel as well.  @leonardpahlke  can we do something regarding the event in the calendar for this?

**Comment by leonardpahlke** [comment]
Sure, good idea! Let me open a ticket to change the title of the meeting invitation.

Thanks @incertum 🙌

**Comment by incertum** [comment]
Thanks for hosting @leonardpahlke cross-posting updates and action items from our tracking issue https://github.com/falcosecurity/falco/issues/2435#issuecomment-1642509056.

Was lovely meeting all of you!

**Comment by leonardpahlke** [comment]
I'm going to close this issue as it relates to a presentation that took place a few weeks ago.
