### ISSUE TITLE
[Action, Cloud Native Sustainability Week] Small gifts for Meetup organizers

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#141]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

Small gifts that can be given to the meetup organizers.

In a separate issue, we track the effort to issue badges via credly #129

**Comment by leonardpahlke** [comment]
@sysnet4admin shared the idea to sending meetup organizers decals. Ref shop: https://store.cncf.io/collections/decals

**Comment by leonardpahlke** [comment]
cc  @mehmetmgrsl

**Comment by sysnet4admin** [comment]
**[ Suggestion ]**

- Item: T-Shirt
- Purpose: 
   - Cloud native sustainability Advertisement even after event. 
   - Promote the event (kind of limited edition) 
- Sample: (Just Sample)
  -  Front
![Front](https://github.com/cncf/tag-env-sustainability/assets/29163931/9c6114a8-91e9-4894-902b-6357e137fb5b)

  - Back
![Back](https://github.com/cncf/tag-env-sustainability/assets/29163931/274f84a9-801c-4ab7-94dd-687cae90c0b9)
