### ISSUE TITLE
[Tracking, Cloud Native Sustainability Week] Artworks

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#149]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

This issue tracks all the efforts which relate to designs and artworks for the cloud native sustainability week.

Designs folder: https://drive.google.com/drive/folders/1JUtrZr-Aajv7j7gJtA4NC04eYxEydRqR?usp=share_link

**Comment by leonardpahlke** [comment]
The design team needs this document filled out https://github.com/cncf/foundation/blob/main/documents/creative_brief_template.md

**Comment by sysnet4admin** [comment]
Created `Brochure samples` under **Designs folder**. 
I hope it will help to develop this task. 
Thank you for your contributing @lifeoncloud (Desginer)

**Comment by leonardpahlke** [comment]
The [creative brief](https://docs.google.com/document/d/1hZql6BoZtFxET1_mBQ-Eks8k-nXkxPjzzzBFK2yyF9U/edit?usp=share_link) was filled out last week and sent to the CNCF.

**Comment by leonardpahlke** [comment]
@Bamistand I am wondering if you would like to work on a presentation template design which we can use for the cloud native sustainability week. Only if you like & have time, please don't feel pressured!!

Link to a blank template presentation https://docs.google.com/presentation/d/1akM30qXqX-SMwnS7OGiZJCJ3YHgpHf4BuN0VkFwG8nI/edit?usp=share_link

**Comment by Bamistand** [comment]
@leonardpahlke Sure! I am happy to work on it. Can you share with me the needed content?

**Comment by leonardpahlke** [comment]
@Bamistand can you take a look at this document. https://docs.google.com/document/d/1hZql6BoZtFxET1_mBQ-Eks8k-nXkxPjzzzBFK2yyF9U/edit#heading=h.8fjbo973qqrk let me know if you need anything else!
