### ISSUE TITLE
[CI] GitHub actions are passing despite fatal errors in workflow scripts

### ISSUE THREAD

**Issue by chalin** [cncf/tag-env-sustainability#156]
It seems that Setup, and the other actions that depend on it, are failing. For example, see this log:

- https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801

Here is an excerpt:

```nocode
Run make lint
Running lint...


Creating network "tag-env-sustainability_default" with the default driver
Creating tag-env-sustainability_lint_run ... 
Creating tag-env-sustainability_lint_run ... done

added [5](https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801#step:3:6)9 packages in 2s

npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice 
1[7](https://github.com/cncf/tag-env-sustainability/actions/runs/5612066527/job/15243289801#step:3:8) packages are looking for funding
  run `npm fund` for details
fatal: detected dubious ownership in repository at '/usr/src/app'
To add an exception for this directory, call:

	git config --global --add safe.directory /usr/src/app
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
...
```

Checks can be setup more directly via NPM dependencies and scripts. This site is small enough that it probably isn't worth trying to optimize checks over only changed files. (My 2 cents :))

/cc @cjyabraham @nate-double-u

**Comment by chalin** [comment]
Again, this site is simple enough that we can probably also avoid using docker for such simple checks.

**Comment by Azanul** [comment]
All actions seem to be passing

**Comment by chalin** [comment]
I've clarified the title of this issue to make the problem clearer: actions are passing despite **fatal errors** in workflow scripts. It's the scripts that are failing, but not being reported. I.e., the actions are pretty much doing nothing atm. /cc @cjyabraham

**Comment by Azanul** [comment]
Let me try to fix this
