### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by chalin** [cncf/tag-env-sustainability#164]
There are a number of broken links, including:

- https://sci-data.greensoftware.foundation/

referenced from the en and ko landscape pages. What should we replace that link with? Maybe: https://greensoftware.foundation/articles/software-carbon-intensity-sci-specification-project?

**Comment by chalin** [comment]
All links in website pages are now valid, except for the one mentioned in the opening comment above. Someone from the TAG will need to confirm what the replacement link should be.

**Comment by leonardpahlke** [comment]
Good catch! cc @catblade
