### ISSUE TITLE
[Tracking] TAG ENV at KubeCon CloudNativeCon NA 2023

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#174]
This issue is used to track TAG ENV activities during [KCCN NA 2023](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/).

Planned activities:
- In person meetup
- Maintainer talk (cc @catblade)

Other ideas:
- Hackathon see #106 
- TAG ENV kiosk (mini booth)
- Stickers: TAG ENV & Cloud Native Sustainability Week edition

**Comment by catblade** [comment]
Probably need an "update the webpage with known Env Sust talks"

**Comment by leonardpahlke** [comment]
yes, will open an issue later
