### ISSUE TITLE
[Action] Add cloud native sustainability related talks at KCCN NA 2023 to the TAG ENV website

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#177]
For KCCN NA and OSS NA, we have added a page on our website under the Events tab to discover all Cloud Native Sustainability talks and share where the TAG will meet during the conference. We plan to do the same for the upcoming KubeCon CloudNativeCon 2023.

https://tag-env-sustainability.cncf.io/events/

**Comment by leonardpahlke** [comment]
ref tracking issue https://github.com/cncf/tag-env-sustainability/issues/174#issuecomment-1693100999

**Comment by Mfonn** [comment]
I would love to help with this, can I get more information on it? @leonardpahlke

**Comment by kumarankit999** [comment]
Ok. If there are any needs, please feel free to involve me.

**Comment by leonardpahlke** [comment]
Hey, thanks! As soon as the schedule is up we will add [another page](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/events) to our website to give an overview of all sustainability related talks at KCCN NA 2023. The schedule should publish soon.

**Comment by leonardpahlke** [comment]
https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/

**Comment by rolarblaze** [comment]
I am open to contributing to this, count me in once the time is right

**Comment by Mfonn** [comment]
Here are the ones I found @leonardpahlke 
- Keynote: Environmental Sustainability in the Cloud Is Not a Mythical Creature - Rimma Iontel, Red Hat; Tammy McClellan, Microsoft; Marlow Weston, Intel; Niki Manoledaki, Grafana Labs
W375 (SKYLINE BALLROOM)

- CNCF Environmental Sustainability TAG Updates and Information - Marlow Weston, Intel
W196AB

- Cutting Climate Costs with Kubernetes and CAPI - Shiva Rezaie & Steve Francis, Sidero Labs
W375E

- Environmentally Sustainable AI via Power-Aware Batch Scheduling - Atanas Atanasov, Intel & Daniel Wilson, Boston University
W179

- Sustainability and Efficiency: Environmentally-Friendly Software Development with Kube-Green - Davide Bianchi, Mia-Platform
-W184

**Comment by leonardpahlke** [comment]
cc @catblade

**Comment by Mfonn** [comment]
@leonardpahlke I have filled out the file using the description on it. Please check it out and let me know if it is what you expected.

**Comment by leonardpahlke** [comment]
Thanks @Mfonn this looks already gret. Can we write the summary of each talk in "our own words" and reduce its length to 2-3 sentences per bullet point? So it better flows and follows the same style of writing.

**Comment by Mfonn** [comment]
@leonardpahlke Thank you, I have taken the points you noted and implemented it can you check it out to confirm if it is what you expected?

**Comment by leonardpahlke** [comment]
Thanks @Mfonn 🙌 , we will refine and continue this a couple of weeks before the conference as soon as we have more details about our meetup and maintainer talk!
