### ISSUE TITLE
[Tracking] Infrastructure for Green Reviews WG

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#184]
#### Description

This issue is created to track and visualize progress on getting the infrastructure that Green Reviews WG requires up and running.
This issue will be tracked as part of the Green Reviews WG task board.

Current status: request for infrastructure has been submitted to CNCF Community Infrastructure Lab (CIL), currently awaiting feedback/confirmation from the owners. Considering possibility to create a service desk ticket. Ref. https://github.com/cncf/cluster/issues/246
...

### Outcome
Successfully provisioned infrastructure (dedicated Node) that Green Reviews WG can use to start implementing and deploying necessary tools for sustainability footprint measurement project.

...

#### Todos

- [x] @nikimanoledaki to send a reminder on TAG Env Slack and GitHub issue mentioned above;
- [x] @mkorbi @leonardpahlke to confirm if service desk ticket needs to be created. If it's needed, assist us with creating the ticket due to lacking permissions of the WG chairs;

...

Co-owner: @nikimanoledaki

**Comment by guidemetothemoon** [comment]
@leonardpahlke can you please add Green Reviews label on this issue so that it appears on the project board? I don't have permissions to do it yet. Thanks! 😊

**Comment by mkorbi** [comment]
service desk ticket was already created some month back and got redirected to open an issue instead

**Comment by guidemetothemoon** [comment]
@nikimanoledaki I'll close this issue since infrastructure has been provisioned for us as per https://github.com/cncf/cluster/issues/246
I will create a separate issue to figure out access control management to the infrastructure.

@leonardpahlke FYI
