### ISSUE TITLE
[Action, Cloud Native Sustainability Week] Blog Series - Cloud Native Sustainability Tools

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#185]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

Besides meetups and a virtual event, the cloud native sustainability week also opens up the opportunity to publish & feature blogs on this topic. There are a number of cloud native sustainability tools which we can highlight. Kube-Green, Scaphandre, Kepler and more come to mind. We could publish articles on those during the week on the CNCF blog & TAG ENV blog. 

#### If you would like to write a blog post please open an issue using this [issue template](https://github.com/cncf/tag-env-sustainability/issues/new?assignees=&labels=blog&projects=&template=blog.md&title=%5BBLOG%5D+%3Cblog-title%3E), Thanks!

**Comment by akelity** [comment]
Hi Leo, definitely involved in this activity!
Is the idea to write multiple articles or just one? 
I can easily write the one about kube-green if you want! If it's a single article, I'd be happy to contribute!

**Comment by leonardpahlke** [comment]
Awesome thanks @akelity :)

**Comment by husky-parul** [comment]
@leonardpahlke Can you explain where can I signup for this blog? I want to blog on the work I have been doing on Kepler and OpenTelemetry work.

**Comment by leonardpahlke** [comment]
Sounds awesome, thanks! Could you open an issue, so we can track it https://github.com/cncf/tag-env-sustainability/issues/new?assignees=&labels=blog&projects=&template=blog.md&title=%5BBLOG%5D+%3Cblog-title%3E 

Looking forward to your blog!

**Comment by marceloamaral** [comment]
The Kepler blog post is live on the cncf blog page: 
https://www.cncf.io/blog/2023/10/11/exploring-keplers-potentials-unveiling-cloud-application-power-consumption/
