### ISSUE TITLE
[Annual-Sandbox-Review-help] TAG Runtime

### ISSUE THREAD

**Issue by rajaskakodkar** [cncf/tag-env-sustainability#196]
Hello 👋 

We at TAG Runtime, need help with the annual sandbox review of the following projects:

- [Akri](https://www.github.com/cncf/toc/pull/1080)
- [SuperEdge](https://www.github.com/cncf/toc/pull/1075)

TAG Runtime has 14 projects to review and is running short on the number of contributors/reviewers. It'd be of great help if TAG Env Sustainability can help out with the review of the above projects. 

Here's the slack message for Coordination: https://cloud-native.slack.com/archives/C03F270PDU6/p1693606163314289

**Comment by Princesso** [comment]
Hi @rajaskakodkar, I'm interested in volunteering to review these projects.

**Comment by asiwaju001** [comment]
Hello @rajaskakodkar, we had this discussion in the Sustainability tag and I would love to take the SuperEdge project. Let me know how to go forward with this

**Comment by leonardpahlke** [comment]
Thanks @Princesso and @asiwaju001 I will sync with my fellow TAG leads and give you guidance how to proceed tomorrow! Thanks for volunteering 🙌 

If anyone else is interested supporting on this feel free to drop a comment!

**Comment by rajaskakodkar** [comment]
Thank you @Princesso and @asiwaju001 for offering to help and thank you @leonardpahlke for the guidance! 

Feel free to add yourselves to the sheet where we are tracking this -- https://docs.google.com/spreadsheets/d/16LFpy6eDXu5SVnrs7klcZgupQN_8UM6LfV4a7J3kink/edit#gid=0

**Comment by Princesso** [comment]
> Thank you @Princesso and @asiwaju001 for offering to help and thank you @leonardpahlke for the guidance!
> 
> Feel free to add yourselves to the sheet where we are tracking this -- https://docs.google.com/spreadsheets/d/16LFpy6eDXu5SVnrs7klcZgupQN_8UM6LfV4a7J3kink/edit#gid=0

Hi @rajaskakodkar I did add my name to the sheet. If you need any more details, I'll be happy to share. On the CNCF slack channel, you can reach me with the username `Bube`

**Comment by rajaskakodkar** [comment]
@Princesso thanks! Let us know if you need any help in conducting the review. Once you have conducted the review, do let us know on slack in the coordination thread pointed above in the issue.

**Comment by krol3** [comment]
hi! I would like to help with the review

**Comment by rajaskakodkar** [comment]
Thank you for reaching out @krol3! Apart from the projects listed out in the above issue, we do need help with other projects too. Can you help out review Tinkerbell? You can assign yourself here https://docs.google.com/spreadsheets/d/16LFpy6eDXu5SVnrs7klcZgupQN_8UM6LfV4a7J3kink/edit#gid=0 and get started with the review. There is a ton of context you can find on scroll back in `#tag-runtime-sandbox-rev` channel on CNCF slack

**Comment by leonardpahlke** [comment]
@rajaskakodkar are we good to close this?
