### ISSUE TITLE
All the navbar elements are not visible at certain width

### ISSUE THREAD

**Issue by VivekBaldha0712** [cncf/tag-env-sustainability#197]
![image](https://github.com/cncf/tag-env-sustainability/assets/86009821/4716b18c-61d5-42cd-857d-e52e89f9529b)

**Comment by Mfonn** [comment]
@VivekBaldha0712 Hi, Can I be assigned this issue?

**Comment by leonardpahlke** [comment]
cc @chalin

**Comment by leonardpahlke** [comment]
Looks like this is a duplicate -> https://github.com/cncf/tag-env-sustainability/issues/167
