### ISSUE TITLE
[Proposal] COMMS WG Charter Review

### ISSUE THREAD

**Issue by caradelia** [cncf/tag-env-sustainability#206]
#### Description
- Review Communications Working Group Charter Proposal

#### Additional info and comments
- Reference to supporting material: Please see TAG ENV_Working Group_Proposal_Comms .pdf

### NEXT STEPS
- [ ] Review Charter and provide feedback
- [ ] Project leader(s): Cara Delia and seeking a co-chair
- [ ] Slack Channel (as needed): Will need to set up
- [ ] Meeting Time & Day: To be determined. Looking at every 2 and 4th Thursday

[TAG ENV_Working Group_Proposal_Comms .pdf](https://github.com/cncf/tag-env-sustainability/files/12620804/TAG.ENV_Working.Group_Proposal_Comms.pdf)
-->

**Comment by AntonioDiTuri** [comment]
The document looks already very good to me, great work!

**Comment by immavalls** [comment]
lgtm!

**Comment by caradelia** [comment]
You can also comment direvtly in the doc. here > https://docs.google.com/document/d/1dVHzNtJB07Nv2JN6ZUkmRflgq3RL9BbaURbgPnGENdk/edit?usp=sharing

**Comment by husky-parul** [comment]
Hi @caradelia 

Thank you for taking the time to organize this document. This is very well written. 
I believe my most useful contribution will be under the following goals, scopes and deliverables. If that aligns with the work group objectives, I am willing to co-lead. LMK

## Goals
- [ ] Provide resources through a review process and methodology to help CNCF projects to evaluate their sustainability footprint[^1] and integrate environmental sustainability practices. 

## Scope
- [ ] Monitor Sustainability events
- [ ] Collaborate with other open source sustainability projects

## Deliverables
- [ ] Content (blogs, white papers, website copy, etc.)

**Comment by guidemetothemoon** [comment]
The charter looks very good, +1. Thanks for the great effort put into this!
Very excited about this WG 😊

**Comment by leonardpahlke** [comment]
@caradelia I added a few comments to the doc

**Comment by leonardpahlke** [comment]
@mkorbi @catblade could you take a look at the gdocs charter proposal. Thanks!

**Comment by guidemetothemoon** [comment]
Closing this issue since Comms WG charter is now reviewed, approved and published.
@caradelia @patricia-cahill @leonardpahlke FYI.
