### ISSUE TITLE
Missing file, "Writingstyle.md"

### ISSUE THREAD

**Issue by Mfonn** [cncf/tag-env-sustainability#208]
The Writing Style file is mentioned in the Contributing Guidelines but on clicking the link, it leads to a 404 Page.
Attached below is the image and the link to the page in question

![image](https://github.com/cncf/tag-env-sustainability/assets/67243684/96299d37-cbea-463d-bdf2-abf4126a8e8f)

https://github.com/cncf/tag-env-sustainability/blob/main/writing-style.md

**Comment by leonardpahlke** [comment]
Thanks @Mfonn for noticing this!

**Comment by kumarankit999** [comment]
Can I help into this

**Comment by leonardpahlke** [comment]
Yes 🙌 you can use this as a reference https://github.com/cncf/tag-security/blob/main/CONTRIBUTING/writing-style.md 

Please draft it up here https://docs.google.com/document/d/1i8CUHXmXElva3gw983Y5PNxw0Y-ab9f2GR7qxNp_jWQ/edit?usp=sharing and request a review once you completed it. Thanks @kumarankit999 !!

**Comment by kumarankit999** [comment]
Yes, I do

**Comment by leonardpahlke** [comment]
@kumarankit999 let us know if you have any questions

**Comment by leonardpahlke** [comment]
@caradelia maybe this effort can be moved to the WG Comms, wdyt

**Comment by kumarankit999** [comment]
I will make it in soon @leonardpahlke

**Comment by kumarankit999** [comment]
Can anyone assign me to this

**Comment by kumarankit999** [comment]
#257 I have created a PR on this

**Comment by kumarankit999** [comment]
#257
