### ISSUE TITLE
[BLOG] Reducing your environmental impact with the Linkerd service mesh

### ISSUE THREAD

**Issue by CathPag** [cncf/tag-env-sustainability#222]
- **Authors**: *Catherine Paganini*
- **Reviewers**: *Jason Morgan, Flynn*
- **TAG ENV Lead**: *TBD* 

## Abstract

Since its inception, Linkerd has always focused on having the smallest possible resource footprint. That makes it not only the most efficient and cost-effective service mesh on the market, but also the most sustainable one. That's because Linkerd helps minimize emissions on various levels. Its small Rust micro-proxy makes it ten times more resource-efficient than Envoy-based alternatives, and thanks to Linkerd's intelligent load balancing, you improve system performance, even compared to using no service mesh.  

#  Reducing your environmental impact with the Linkerd service mesh

In the complex world of service meshes, Linkerd is known for its simplicity. But Linkerd has also focused on having the smallest possible resource footprint since its inception. That makes it not only the most efficient and cost-effective service mesh on the market but also the most sustainable one. In fact, due to its intelligent load balancing, adding Linkerd to your stack can actually reduce the overall resource footprint of your system as a whole. Too good to be true? It sounds like it, but it actually pans out. 

##  Resource consumption, a great proxy for environmental impact 

Sustainability is, unfortunately, still an afterthought when it comes to computer systems. That's why we are thrilled to see the TAG for Environmental Sustainability shining a light on this important topic and pushing for change. This lack of focus also means that we don't yet have a really precise way of measuring the environmental impact of our systems. However, there is a good proxy for it: resource consumption. Generally speaking, the more resources your system consumes, the higher the environmental impact. 

##  Linkerd's Rust-based micro-proxy

Almost every service mesh other than Linkerd uses the Envoy proxy — a powerful proxy that can do much more than a service mesh needs. While Envoy is a great project, using a big general-purpose proxy for a very narrow use case, like the service mesh, is very inefficient. 

Linkerd took a different approach. It is the only service mesh with a [purpose-built micro-proxy written in Rust](https://linkerd.io/2020/12/03/why-linkerd-doesnt-use-envoy/). It was designed specifically for service mesh use cases, and because the range of features needed is very specific, the Linkerd proxy is the smallest and most resource-efficient service mesh proxy. It uses only a [tenth of the resources (CPU and memory) that Envoy does](https://linkerd.io/2021/11/29/linkerd-vs-istio-benchmarks-2021/index.html). (While "sidecar-less" service meshes exist, they work by deploying larger, per-host proxies and come with significant security and operational caveats — see our writeup on [eBPF, sidecars, and the future of the service mesh](https://buoyant.io/blog/ebpf-sidecars-and-the-future-of-the-service-mesh)).  

##  Additional software = bigger resource footprint? Not necessarily.   

Each additional piece of software translates into consuming more system resources, right? In theory, yes, but if it helps you run your system more efficiently, you may actually decrease your footprint. 

The environmental impact of adding features such as zero-config and in-transit encryption (mTLS), as provided by Linkerd, is not zero — no software is. Whether you think that environmental (and financial) cost is viable or reasonable is a different discussion. But you might be surprised to hear that Linkerd can minimize your impact even when compared to no service mesh. That's thanks to Linkerd's intelligent load balancing. But let's take a step back and examine how Kubernetes works first.

##  Distributing work in Kubernetes vs. Linkerd 

Kubernetes allows us to more densely pack processes on computers. Servers have a certain capacity to do work, but there is always a gap between how much work they _can_ do and how much the system asks them to do. Kubernetes schedules work more efficiently on existing servers (bin packing), allowing us to run more stuff on the same hardware — a big win! 

Linkerd improves those efficiency gains even further by taking a different approach to endpoint selection. While Kubernetes balances its load based on connections, Linkerd instead does it based on requests. As a result, Linkerd saves you significant compute resources. Let's break that down.  

In the old world, applications would make one connection, send a request, get an answer, and close that connection — not very efficient when you have hundreds or thousands of requests per minute. Today, HTTP/2 and gRPC make a connection once and send multiple requests to avoid this inefficiency.

Kubernetes doesn't handle that out-of-the-box, though. Natively, Kubernetes simply directs the entire connection to a Pod and doesn't worry about how many requests are coming down the connection. This can be problematic: if you're running 10 Pods for a particular workload, and 50 requests come down a single connection, Kubernetes will send all 50 to the same single Pod. In the best case, the other nine Pods just sit idle; in the worst case, the one Pod doing all the work wasn't sized for this peak load, resulting in a crash.

This inefficiency happens because Kubernetes wasn't designed to look inside the connection and decipher each request – doing so requires a lot of knowledge of what exact protocol is being spoken, and is far out of scope for Kubernetes itself. As Kelsey Hightower famously said, "[Kubernetes is a platform for building platforms](https://twitter.com/kelseyhightower/status/935252923721793536)" – Kubernetes never intended to solve that particular problem since other projects could.

##  Minimizing unusable resources 

Imagine you want to fill up a box with rocks. The smaller the rocks, the less wasted space (air gaps between rocks). The same applies to Pods: sizing by peak demand tends to leave much larger amounts of unused capacity, requiring more Pods and costing you money. Allowing sizing Pods by average demand instead of peak demand, as discussed above, lets you get more out of your existing resources by not forcing you to leave unused capacity just in case, improving your horizontal scalability by allowing you to run more smaller Pods.

This means that under load, Linkerd can distribute traffic across Pods much more effectively since it _does_ do the work to understand the protocol and be able to load-balance individual requests. This allows you to assign fewer compute resources to each Pod because you know the load will be equally distributed, and you, therefore, don't have to dedicate huge amounts of resources to the possibility of huge spikes. For example, Entain Australia, a sports betting company, wrote a great [CNCF case study on how Linkerd helped them significantly reduce latency and cost](https://www.cncf.io/case-studies/entain/) thanks to intelligent load balancing. 

This approach is not only more resource-efficient and environmentally friendly, requests are also processed faster because they aren't stuck in an overloaded pod queue. And since Linkerd is deliberately trying to choose low-latency Pods, the overall user experience can be better since overall latency is reduced.

##  Simplicity = sustainability

As we've seen, Linkerd can help you minimize your resource footprint in various ways. First, its small Rust micro-proxy makes it ten times more resource-efficient than Envoy-based alternatives (basically every other service mesh). Thanks to its intelligent load balancing, you can improve overall resource usage compared to using no service mesh. While the Linkerd team didn't set out to build the most sustainable service mesh on the market, our[ focus on simplicity and resource efficiency](https://linkerd.io/design-principles/) made it so. Sustainability is certainly an important area that is finally getting more attention. We are proud that our design principles align well with the TAG for Environmental Sustainability's mission — even if it was more accidental than planned. 

_Thanks to Jason Morgan and Flynn for walking me through it. I learned a lot and hope the readers will, too._

**Comment by leonardpahlke** [comment]
Thanks @CathPag! Its very well written. /lgtm

**Comment by catblade** [comment]
My understanding was that linkerd and Kubernetes work together, so I'm confused with the vs. Title.  Could you expand on that please?  Is it possible to add an analysis of what the restrictions on this are to normal K8s deployments?  Does it play nicely with the scheduler, for instance?

**Comment by CathPag** [comment]
Yes, that is correct. They both work well together and focus on different things. However, both can handle load balancing, but Kubernetes and Linkerd take a different approach.

> While Kubernetes balances its load based on connections, Linkerd instead does it based on requests. As a result, Linkerd saves you significant compute resources. Let's break that down.

Kubernetes wasn't designed to optimize load balancing — that was never in the project's scope. That is one of the things service meshes like Linkerd handle. 

> [...] Kubernetes wasn't designed to look inside the connection and decipher each request – doing so requires a lot of knowledge of what exact protocol is being spoken, and is far out of scope for Kubernetes itself. As Kelsey Hightower famously said, "[Kubernetes is a platform for building platforms](https://twitter.com/kelseyhightower/status/935252923721793536)" – Kubernetes never intended to solve that particular problem since other projects could.

I hope that helps.

**Comment by catblade** [comment]
> Yes, that is correct. They both work well together and focus on different things. However, both can handle load balancing, but Kubernetes and Linkerd take a different approach.

Apologies-I'm still confused.  My understanding is that linkerd is a service mesh that runs with K8s.  I'm confused at the vs. piece.  Is it rather that linkkerd can take over the load balancing instead of stock K8s?

**Comment by CathPag** [comment]
That's correct. Linkerd is a service mesh, and Kubernetes is a container orchestrator. But both can handle load balancing. Kubernetes does a so-so job at it because, as mentioned above, that's not what it was designed to do. Linkerd does it better because that's the area where service meshes shine. In short, two different tools with some overlap (aka load balancing). 

That specific section talks about how Linkerd _handles load balancing_ vs. Kubernetes does that. It's not Linkerd vs. Kubernetes per se. It's Linkerd's approach to load balancing vs. Kubernetes' approach to it.

Does that clarify it?

**Comment by catblade** [comment]
It does!  Okay, so with that in mind, can we instead use "native K8s load balancing", or something around that, in the blog post above as an edit please?  That would really help avoid confusion (at least, if there are any me-clones running about).

**Comment by mkorbi** [comment]
Thanks for writing this up, it is an interesting perspective.  
lgtm

Do we have already a PR for it?

**Comment by guidemetothemoon** [comment]
Very interesting and well-written blog post, thank you for your contribution!☺️

I remember when I used Linkerd for the first time I was positively impressed about how lightweight and straightforward it was. Not surprising to read how it aligns with the goals for a sustainable solution, even though it was initially accidental. But going forward I guess it wouldn't be that accidental anymore, in terms of further development? 😁

**Comment by CathPag** [comment]
@catblade, done!

@mkorbi, not yet. Leo only mentioned the issue. Happy to create one.

@guidemetothemoon, yes! Sustainability is incredibly important. Gald it happened accidentally, and definitely something to pursue deliberately.

**Comment by leonardpahlke** [comment]
Thanks @CathPag 😊

**Comment by catblade** [comment]
Hello @CathPag!  Thank you for the changes.

I am going to ask for a couple of more modifications.  Could you turn

> Distributing work in Kubernetes vs. Linkerd

into

> Distributing work in Native Kubernetes vs. using Linkerd

- I'm also trying to figure out how to articulate that K8s proper scheduling is reliant on scheduling plugins for locations.  It ends up being a complicated problem, and not overly intelligent without intelligent solutions such as KEDA.  As I read this, the load balancing of the connections happens AFTER the deployment of the pods.  Also, sometimes those pods may be distributed across the cluster, on various regions, so absolutely the fact that Linkerd intelligently distributes those is extra helpful, so not bin-packed, because if they were bin-packed, the connections would be slower depending on the amount of traffic involved.  You don't want all the same traffic going to the same node, for example.  Maybe something with that first paragraph in the section on distributing work should be changed.  Would it be helpful for us to spend some time going through and modifying, or would you like to take another push at it?  I'm really happy to help here.  I think this is really helpful and useful content.  

- Some of the other service meshes have added a bunch of items on top of the classic service mesh functionality, making it difficult to use just the functionality you are interested in.  It isn't just the rust proxy that makes you faster, although that certainly helps.  Unfortunately, other projects such as Kubeflow use other service meshes that are envoy-based.   I would like something in this blog post around changing projects to allow for simpler service meshes.  A re-imagining of SMI would be awesome, if we could swing it, to replace the hard-coded service mesh pieces of other projects.  Given the way AI/ML is taking off, I'd really like to see the heavier weight service meshes replaced when the extra functionality built into them is not needed.

- I'd remove the "even if it's more accidental than planned."  It's planned, in that you were working on efficiency, which tends to also be often in the same boat with sustainability.  You guys have done an awesome job with the service mesh there.

**Comment by CathPag** [comment]
Thanks, @catblade. Let me and the team go over your suggestions and get back to you. Regarding the accidentally comment, I'd kindly ask you to keep it.  It's a fun ending, making it more engaging.

**Comment by catblade** [comment]
@CathPag  It is your blog post!  No issue with keeping it-everything I add is suggestions only, as it is YOUR post, and it is fun.  :-)

**Comment by catblade** [comment]
@CathPag Also, while I'm asking for the world, should we add linkerd maybe to the sustainability landscape document?  It is here:  https://github.com/cncf/tag-env-sustainability/blob/main/website/content/landscape/_index.md

**Comment by CathPag** [comment]
Yes, please, @catblade. We'd love to be included! 💙

Here's some feedback from our team regarding your suggestions:

> Scheduling and load balancing are orthogonal to each other. Load balancing does indeed happen _after_ all the decisions made in terms of scheduling, but that means that Linkerd can’t affect scheduling. So it makes sense for a post at this level to only discuss load balancing and to ignore scheduling. A follow-up talking about scheduling would definitely not be a bad thing (there are also implications for power consumption there), though we’d need to partner with a domain expert there.
> 
> Likewise, talking about e.g., tweaking Kubeflow to use Linkerd is a great idea, but outside the scope here. (Gateway API might be the best route forward there, FTR.) That’s another area where partnering would be the way to go: work with Kubeflow to show them running on Linkerd to improve sustainability, then write about it.

What do you think about postponing that for a follow-up blog post?
