### ISSUE TITLE
[Suggestion] i18n for website

### ISSUE THREAD

**Issue by SamYuan1990** [cncf/tag-env-sustainability#251]
#### Description
To make i18n support for our website

...

#### Impact

To make more people understand us better with their local language.

...

#### Scope

Our website.

...

#### Additional info and comments
- Reference to supporting material: `NONE`
- Links to related site: `NONE`
- Feel free to delete this section if you don't have more info: `NONE`

**Comment by leonardpahlke** [comment]
cc @chalin

**Comment by leonardpahlke** [comment]
I dont now too much about i18n at the moment. Perhaps @chalin knows more about it.

**Comment by guidemetothemoon** [comment]
@SamYuan1990 @leonardpahlke this issue is now resolved, right?

**Comment by SamYuan1990** [comment]
> @SamYuan1990 @leonardpahlke this issue is now resolved, right?

yes
