### ISSUE TITLE
[Action] CNCF Cloud Native Sustainability Week - Add YouTube recording links to website page

### ISSUE THREAD

**Issue by mrchrisadams** [cncf/tag-env-sustainability#254]
It’s really nice to see so many talks and events put together for [CNCF Sustainability week](https://tag-env-sustainability.cncf.io/cloud-native-sustainability-week/#events).

Is there a central place to see the decks and recorded talks that were shared after the events?

The page lists the events, but it’s less clear to me where to look for the uploaded materials and recordings, and there were some fantastic decks from earlier events.

**Comment by mrchrisadams** [comment]
Ah, I've just seen this issue. It suggests to me that there will be at least one place where a significant share of uploaded talks will be accessible:

https://github.com/cncf/tag-env-sustainability/issues/133

**Comment by leonardpahlke** [comment]
Yes, we are working on getting recordings uploaded to YouTube this week. We have a few in person meetup recrdings next to the virtual meetup. 

All recordings will be uploaded to our YT channel:https://www.youtube.com/watch?v=8G248SnpRkc&list=PL_3_oSSuNpD4cdUFtW68Ejl5FpD7fEFdg

**Comment by leonardpahlke** [comment]
cc @Nancy-Chauhan

**Comment by leonardpahlke** [comment]
We have a link on the website to the recordings on YT
