### ISSUE TITLE
[Suggestion] Add process for creating new TAG ENV communication channels

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#258]
#### Description

As part of Green Reviews WG lifecycle we had a need to create a new Slack channel where WG specific discussions can take place. In addition we have recently created a TAG ENV LinkedIn page and with all the uncertainties around Twitter/X there may be a need to utilize additional social media platforms for TAG ENV communication in the future. In case new WGs will be created there may once again be a need to create a new Slack channel for instance.

In order to minimize uncertainty and repeating questions it can be beneficial to have the process outlined and put in writing as part of the TAG ENV governance folder. It doesn't need to be long but should outline a few steps that must be completed once a new communication channel is created, like f.ex. approval from TAG ENV lead, update README, website, etc.

Changes related to this are part of following PR: #252 

#### Impact

This change will make the process clear and transparent once there will be a need to create a new communication channel in the future. Once the process is defined and put in writing we will also minimize repeating questions and uncertainty around how such changes should be done.

#### Scope

Changes are done in #252 

@leonardpahlke FYI.

**Comment by leonardpahlke** [comment]
Thanks @guidemetothemoon, I think that is a great addition to the governance.

**Comment by leonardpahlke** [comment]
We may want to create a generic issue template for this purpose. "proposal to create a new slack channel for WG XYZ" / "proposal to utilize the social media platform XYZ"

**Comment by guidemetothemoon** [comment]
Thanks @leonardpahlke ! Great suggestion regarding the issue template, I have now added it to #252.
