### ISSUE TITLE
Access to add Guatemala to the sustainability week

### ISSUE THREAD

**Issue by sergioarmgpl** [cncf/tag-env-sustainability#259]
My user to add a PR for the sustainability week is @sergioarmgpl, it is for the Cloud Native Guatemala

**Comment by sergioarmgpl** [comment]
@leonardpahlke I just need access to push my branch :) and then a PR

**Comment by leonardpahlke** [comment]
You can open a PR by forking the repository first. 

![Screenshot by Dropbox Capture](https://github.com/cncf/tag-env-sustainability/assets/58054077/c67efc3c-3f3d-43c6-9e95-62c5cfb449b4)

**Comment by leonardpahlke** [comment]
1. fork repository
2. clone forked repo from your GH namespace
3. new branch `git checkout -b <branch name>
4. make changes in the [file](https://github.com/cncf/tag-env-sustainability/edit/main/website/content/cloud-native-sustainability-week/_index.md)
5. push changes `git push --set-upstream origin <branch name>
6. navigate to your repo in GitHub
7. open the PR section and open a new PR
8. source branch: the local one you made changes, target branch: [tag-env-sustainability:main](https://github.com/cncf/tag-env-sustainability/tree/main)

**Comment by leonardpahlke** [comment]
This is the common workflow across OSS. Perhaps it would be good to update our [CONTRIBUTING.md](https://github.com/cncf/tag-env-sustainability/blob/main/CONTRIBUTING.md#before-your-first-pr) with a more thorough guide.

cc @patricia-cahill @caradelia

**Comment by guidemetothemoon** [comment]
Closing this PR since the link for Guatemala meetup is now added to the website.
