### ISSUE TITLE
[Action] move cloud native sustainability website page under the event page

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#278]
The cloud native sustainability week was a big success. The link to the event is on the front page of our website. We would like to move the [cloud native sustainability week page](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/cloud-native-sustainability-week) under the [event page](https://github.com/cncf/tag-env-sustainability/tree/main/website/content/events).

- The link to the event page tag-env-sustainability.cncf.io/cloud-native-sustainability-week should persits after moving the page. This can be achived [an alias in the frontmatter of the page](https://bwaycer.github.io/hugo_tutorial.hugo/extras/aliases/) (see [comment](https://github.com/cncf/tag-env-sustainability/pull/271#issuecomment-1811664077)).

see discussion: https://github.com/cncf/tag-env-sustainability/pull/271#issuecomment-1810463142

cc @SamYuan1990

**Comment by SamYuan1990** [comment]
@leonardpahlke , please help check with the PR :-)

**Comment by leonardpahlke** [comment]
merged ✅
