### ISSUE TITLE
[Action] Load generation / k6 evalution and discussion

### ISSUE THREAD

**Issue by matthewi** [cncf/tag-env-sustainability#287]
#### Description
Continuing the discussion from https://github.com/cncf/tag-env-sustainability/issues/182#issuecomment-1752902159 and this week's wg meeting.

K6 provides a way generate and manage a distributed network load for testing applications. It does not provide a mechanism for running lower level stress tests.

High level questions:
- Is K6 the right tool for network loads for the project?
- Do we want to use a separate tool for managing lower level stress tests for load generation?
- Do we need both cases to be handled by 1 tool? Does such a tool exist?

K6 open questions:
- What method do we use to operate the runners?
   - the SaaS cloud is easy but long term we want to limit external clouds and leverage community resources when possible.
   - k6-operator: this was recommended as the simplest way to get started.
      - Con: since the load is coming from within the cluster it will mean we can't run end to end network tests with projects such as Istio.
      - We should prevent the runners from scheduling on the node(s) used by Falco (or other project(s) being tested)
- technical requirements for the load test itself - number of VUs, duration, failure/success thresholds, etc. (This generally applies to any network load generator)

K6 Resources:
* [Sample application and test scripts](https://github.com/grafana/quickpizza/tree/main/k6)
* [Prometheus stats output](https://k6.io/docs/results-output/real-time/prometheus-remote-write/)
* [k6-operator](https://github.com/grafana/k6-operator)
      

...

### Milestones

...

### Input

...

### Outcome

...

#### Todos

...

**Comment by leonardpahlke** [comment]
@nikimanoledaki @AntonioDiTuri added the issue/needs-triage label.

**Comment by nikimanoledaki** [comment]
We will not be using k6 as part of the benchmarking in WG Green Reviews after all so we can close this issue and re-open it if this changes. @matthewi it would be great to have your input on the new proposals being drafted regarding this! https://github.com/cncf-tags/green-reviews-tooling/issues/83
