### ISSUE TITLE
should we enhance link check validation or disable it?

### ISSUE THREAD

**Issue by SamYuan1990** [cncf/tag-env-sustainability#288]
https://www.researchgate.net/publication/333062266_Improving_Data_Center_Efficiency_Through_Holistic_Scheduling_In_Kubernetes is available but fails with link check https://github.com/cncf/tag-env-sustainability/actions/runs/6980894981/job/18996999652?pr=271#step:7:251

**Comment by leonardpahlke** [comment]
cc @guidemetothemoon

**Comment by guidemetothemoon** [comment]
@SamYuan1990 unfortunately some of the Cloudflare-hosted websites have too strong protection against web scraping which causes automated tools like `markdown-link-check `to return a `403` error upon accessing such websites. I've tried a bunch of different workarounds like using all the HTTP headers that are used when the website is accessed via regular browser, but still didn't get it to work. I suggest to go the smoother route here: if you've verified that the link is valid an accessible via browser, please add a `<!-- markdown-link-check-disable-next-line -->` flag right before the line with the link to disable checking of that link. 

I will also add a note on this to our contribution doc.

**Comment by guidemetothemoon** [comment]
Closing this issue since resolution is added to this thread.
