### ISSUE TITLE
[Action] Update comms information with the new TAG ENV calendar

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#291]
Hey, we created a new TAG ENV calendar. We need to update our website and general communication information so folks can look at the calendar.

* We could also think about adding the cal to our website: `<iframe src="https://calendar.google.com/calendar/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1%40group.calendar.google.com&ctz=America%2FChicago" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`
* Link to calendar: https://calendar.google.com/calendar/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1%40group.calendar.google.com&ctz=America%2FChicago

- [ ] Update calendar links in the repo content, including website once we have the calendar embedded.

**Comment by professorabhay** [comment]
Hey, @leonardpahlke! I would like to work on this. 
Can you please give more exposure about it?

**Comment by leonardpahlke** [comment]
Great! We need to update the https://github.com/cncf/tag-env-sustainability/blob/main/README.md and https://github.com/cncf/tag-env-sustainability/blob/main/website/content/_index.md + we would like to explore if we can add the calendar via iframe to the hugo website and if so, how it looks like`<iframe src="https://calendar.google.com/calendar/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1%40group.calendar.google.com&ctz=America%2FChicago" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`

**Comment by kumarankit999** [comment]
I would like to work on this! @leonardpahlke

**Comment by leonardpahlke** [comment]
Awesome! Feel free to open a PR ☺️

**Comment by leonardpahlke** [comment]
Closed https://github.com/cncf/tag-env-sustainability/pull/305
