### ISSUE TITLE
Nomination Green Reviews WG Tech Lead: Ross Fairbanks

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf/tag-env-sustainability#292]
Dear TAG ENV and Green Reviews WG members, 

The [Green Reviews WG](https://github.com/cncf/tag-env-sustainability/tree/main/working-groups/green-reviews) has an open need for a Tech Lead (TL) who will help lead the design and implementation of the sustainability assessment pipeline and its various components. It is my pleasure to nominate Ross Fairbanks (@rossf7) for the TL role for the Green Reviews WG.

Ross has been an invaluable member of TAG ENV and throughout the bootstrapping process of the Green Reviews WG. He has spearheaded the design and implementation of the pipeline through his active technical contribution to the infrastructure, cluster, and application provisioning, among other things. He has been stewarding the project's technical work through issues and PRs while leading the open-source community discussions in the WG's various spaces, including the WG and TAG repositories, TAG & WG meetings, design document, etc.

In the broader open-source cloud-native ecosystem, Ross has contributed to the implementation and advocacy through talks and blog posts for tooling used to gather proxy metrics for environmental sustainability. He contributed code to Scaphandre's Kubernetes integration, led discussions about Kepler, and authored a blog post about KEDA's carbon-aware scheduling feature, among other things.

Please consider this nomination for Ross. His expertise and wealth of knowledge will be of tremendous help to continue the project forward as we continue to develop the pipeline, implement its various components, and continue our collaboration with CNCF project maintainers.

All community members are welcome to vote by leaving a comment on this issue. Votes are non-binding for community members and binding for TAG Chairs & TLs.

As mentioned in the [TAG ENV Governance](https://github.com/cncf/tag-env-sustainability/blob/main/governance/lead-proposal-process.md#submitting-a-nomination-for-working-group-and-project-leads): 
> Community nominations will run for at least 2 weeks, with a maximum up to 1 months. The TAG Chairs will take a vote. Upon close of nominations, a decision should be made within the next month.

Regards,

Niki

**Comment by AntonioDiTuri** [comment]
I vote for @rossf7!

**Comment by immavalls** [comment]
NB vote for Ross!

**Comment by mkorbi** [comment]
+1 binding

**Comment by russelltrow** [comment]
A vote for @rossf7!

**Comment by leonardpahlke** [comment]
+1 B — thanks for all the work! 🙌

**Comment by caradelia** [comment]
+1 NB

**Comment by catblade** [comment]
+1 Binding.

**Comment by leonardpahlke** [comment]
The nomination is now open for over two weeks and passed the vote. I opened the PR to add @rossf7 as a TL to WG Green Reviews. Thank you very much for your volunteering and congratulations!
