### ISSUE TITLE
[Action] Add WG Comms information to our website and repo

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#299]
Hey, we would like to add WG Comms info to our website & tag repo by following the pattern WG Green Reviews established.

- [x] Add WG Comms to website https://github.com/cncf/tag-env-sustainability/tree/main/website
- [x] Add README to the repo, right now we just have the charter doc https://github.com/cncf/tag-env-sustainability/tree/main/working-groups/comms
- [x] Add WG Comms reference to TAG read me https://github.com/cncf/tag-env-sustainability/tree/main#working-groups

cc @caradelia @patricia-cahill

**Comment by guidemetothemoon** [comment]
I'm working on updating Slack channel information so I can fix this at the same time, as part of the same PR 😊
