### ISSUE TITLE
[Tracking/Action] update zh content with glossary and Fixed Emoji Display 

### ISSUE THREAD

**Issue by SamYuan1990** [cncf/tag-env-sustainability#306]
#### Description

I noticed there some recent update on https://github.com/cncf/tag-env-sustainability/tree/main/website/content/en/glossary and https://github.com/cncf/tag-env-sustainability/pull/298 and I want to apply them to zh content pages.
...

### Milestones

...

### Input

...

### Outcome

update zh page content with glossary and fix emoji Display
...

#### To-Do

...

**Comment by guidemetothemoon** [comment]
Closing issue since it's fixed by #315
