### ISSUE TITLE
[Action] Survey at Kubecon in collaboration with LF Research

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#309]
Action item, part of the Kubecon planning meeting (12th of Dec 2023). We would like to reach out to LF research to craft a cloud native sustainability survey which we will share at Kubecon EU 2024. We would like to know if LF research could collaborate with the TAG to analyze the survey afterwards to send out a report.

/assign @caradelia

**Comment by nikimanoledaki** [comment]
I would be happy to help with this! Please count me in :)

**Comment by leonardpahlke** [comment]
The CNCF already worked on a cloud native sustainability survey which they will release anytime now. I would tend to close this since we already have a comprehensive survey + the survey which we distributed during the cloud native sustainability week has not yet been analyzed and i fear this may happen again.

**Comment by leonardpahlke** [comment]
@caradelia and all, let me know what you think. Would be good to discuss this in a wg comms meeting.
