### ISSUE TITLE
[Action] ContribFest at KubeCon EU 2024 around measuring the cloud native footprint of CNCF projects

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#310]
Action item, part of the Kubecon planning meeting (12th of Dec 2023). We would like to reach out to the Co-Chairs of Kubecon about organizing a contribfest around measuring the cloud native footprint of CNCF projects.

cc @nikhita @kaspernissen @aparna-subramanian

**Comment by nikimanoledaki** [comment]
I'd like to help with this! 🙋‍♀️

**Comment by leonardpahlke** [comment]
ContribFest is a format for sandbox, incubation and graduated projects
