### ISSUE TITLE
[Tracking/Action] Website + Glossary translation to Spanish Language

### ISSUE THREAD

**Issue by sergioarmgpl** [cncf/tag-env-sustainability#322]
#### Description
Add the Spanish language to the Env Sustainability website and the Glossary

### Input
Just the current content of the website

### Outcome
Website translated into Spanish

#### To-Do
Translate the current pages

**Comment by sergioarmgpl** [comment]
I am going to work on the About folder

**Comment by JuanPabloGarciaMonzon** [comment]
I will be part of the translation team from Cloud Native Guatemala.

**Comment by Dianmz** [comment]
I will be helping with the translation. I'm from Cloud Native Guatemala

**Comment by jossiebk** [comment]
I´m gonna be part of the translation team from Cloud Native Guatemala.

**Comment by shlopezm4** [comment]
Hello, I'll also be part of the translation team. I'm a member of Cloud Native Guatemala.

**Comment by sergioarmgpl** [comment]
We already assigned the 23 documents to translate into our team. This will be ready by February 13th @leonardpahlke 
<img width="583" alt="Screenshot 2024-01-30 at 21 43 26" src="https://github.com/cncf/tag-env-sustainability/assets/26422502/2e56c492-9061-4734-b834-0c6014dd6347">

**Comment by guidemetothemoon** [comment]
Wow, this is amazing! I love all the engagement and efficiency from the community on this - thank you for the time and effort💚

**Comment by sergioarmgpl** [comment]
We are done with @shlopezm4 and I, just waiting for the others translations to send the PR.

**Comment by MRJeff99** [comment]
My part was merged.

**Comment by JF1799** [comment]
My part was merged.

**Comment by yimmirp** [comment]
I'm from the Cloud Native Guatemala Community and I'm happy to help with translations!

**Comment by sergioarmgpl** [comment]
Working on the PR right now @leonardpahlke I think that is related to the other issue pending about the workflow for preview the website into Spanish

**Comment by sergioarmgpl** [comment]
This our current PR https://github.com/cncf/tag-env-sustainability/pull/340 @leonardpahlke

**Comment by leonardpahlke** [comment]
Thanks for all your work translating the website in spanish! 🙌
