### ISSUE TITLE
[Action] Schedule a monthly Asia friendly TAG meeting

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#323]
We would like to start monthly Asia friendly meetings and need to find a timeslot that fit. The meeting can either be Europe + Asia friendly or North America + Asia friendly. The meeting should serve folks in China, Korea, India, Australia and any other Asia countries to attend and participate in the TAG. 

1. Send out a Doodle or similar link to the TAG to vote on a new meeting time. 
2. Promote the doodle to folks in the Asia area
3. Discuss with the TAG Leads the results, find available hosts (min 2) and get the new meeting scheduled.

fyi @cncf/tag-env-sustainability

**Comment by leonardpahlke** [comment]
cc @caradelia @patricia-cahill

**Comment by guidemetothemoon** [comment]
A quick update after today's WG Comms discussion - @caradelia will create and share a Doodle and I'll be happy to cross-share it on the TAG's social media to reach a broader community.

**Comment by caradelia** [comment]
Created a Doodle poll: https://doodle.com/meeting/participate/id/e0Aoymya and sent out today to #tag-environmental-sustainability in Slack. Will also send vial mailing list.

**Comment by SamYuan1990** [comment]
I am not sure if we can extend the poll after Lunar new year. I am planning translate https://www.cncf.io/blog/2024/01/29/cloud-native-sustainability-week-2023-putting-sustainability-on-the-community-radar/ into Chinese and publish it on local social media after lunar new year holiday. Via the local social media and the blog to  let more people know this poll activity.

**Comment by guidemetothemoon** [comment]
@SamYuan1990 if there are any posts/links that should be re-shared on the TAG's social media accounts, please add them here, in Slack or just tag me directly😊

**Comment by SamYuan1990** [comment]
> @SamYuan1990 if there are any posts/links that should be re-shared on the TAG's social media accounts, please add them here, in Slack or just tag me directly😊

hi @guidemetothemoon , with help from LF, we had published this github ticket to local social media via https://mp.weixin.qq.com/s/f_O7LksENts3I_LIXaDPQA

**Comment by guidemetothemoon** [comment]
Great @SamYuan1990 , thanks for sharing! Will re-share it on the TAG's social accounts as well☺️

**Comment by leonardpahlke** [comment]
@caradelia i think we scheduled the first Asia friendly meeting right? When was it again, do we have a host? Could you update this issue - thanks!!

**Comment by SamYuan1990** [comment]
can we safe the calendar into a specific file so that I can import the file locally without access google?

**Comment by saiyam1814** [comment]
> cc @saiyam1814

The maximum votes on the previous Doodle was for 6pm IST/9:30 pm Tokyo time. 
Should we keep Biweekly alternating on Tuesday's? I am happy to help facilitating this.

**Comment by leonardpahlke** [comment]
yes, lets go ahead with this time for now. We may adjust after the first meetings depending on the feedback 👍

**Comment by leonardpahlke** [comment]
> can we safe the calendar into a specific file so that I can import the file locally without access google?

hm, good point. We need to make sure folks can access the meetings properly. The good thing about google cal is that you can opt in and subscribe, but you dont have to and can still explore the events. Low barrier tool which gets the job done. But if its restricted in some palced we need to find a work around. I would stick for google cal for now since it does a great job for now and i would like to avoid jumping tools frequently.

Ad-hoc, as a work around - we could share an .ical file with the meeting series (as soon as we have a meeting series setup). Happy to explore other options!

**Comment by leonardpahlke** [comment]
APAC Meetups are happening for a while now! 🚀  closing this issue.
