### ISSUE TITLE
[Action] Apply for 1Password Open Source

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#336]
The TAG manages a couple of passwords and secrets. It would be great if we could store them in a password manager. There is a 1Password open source program which we could use. https://github.com/tale/1password-teams-open-source/blob/main/README.md This program is recommened to be used by the CNCF.

Does someone has time to manage this @mkorbi @catblade @caradelia @guidemetothemoon 
```[tasklist]
### Tasks
- [x] Update documentation with information for credentials management (including how to access 1Password)
```

**Comment by guidemetothemoon** [comment]
I can look into it.

**Comment by guidemetothemoon** [comment]
Account created and pull request opened: https://github.com/1Password/1password-teams-open-source/pull/903
We also need to agree upon where we store master password and recovery keys for the account, but we can take it in a lead group meeting.
