### ISSUE TITLE
[Presentation] KubeCon EU 2024 Booth presentation

### ISSUE THREAD

**Issue by patricia-cahill** [cncf/tag-env-sustainability#348]
First edit of the slide deck for the KubeCon EU 2024 Booth
This is just the initial draft and needs to be updated, please review and add as you see fit

Link: https://docs.google.com/presentation/d/1XSqBUUx1pMgcBEd05Txd-iFWW5zccanx/edit?usp=sharing&ouid=116491369110669949344&rtpof=true&sd=true

**Comment by leonardpahlke** [comment]
updated the link to : https://docs.google.com/presentation/d/1XSqBUUx1pMgcBEd05Txd-iFWW5zccanx/edit?usp=sharing&ouid=116491369110669949344&rtpof=true&sd=true — the file is in our shared google docs drive

**Comment by guidemetothemoon** [comment]
I think that the slides look good now! Great work😃

**Comment by guidemetothemoon** [comment]
@patricia-cahill @claire-fletcher I created a "Templates" folder in WG Comms -> EVENTS folder in Google Drive and copied the booth presentation slides there for future re-use. https://drive.google.com/drive/folders/1lhNeobXAVhv_R7cXXZM0Xj4a2S7UcbAk?usp=drive_link
Closing this issue.
