### ISSUE TITLE
[RETRO] KubeCon+CloudNativeCon Europe 2024

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#353]
This tracking issue is a used to collect async retro items from anyone who attended KubeCon+CloudNativeCon Europe 2024.

Please use the following template to leave feedback:

* **KEEP DOING**:
* **MORE OF**:
* **START DOING**:
* **STOP DOING**:
* **LESS OF**:
* **IDEAS**:

We will discuss anything added to the issue in the upcoming retro meeting and report on the results in one of the upcoming TAG Meetings.

cc @cncf/tag-env-sustainability

**Comment by claire-fletcher** [comment]
It was amazing to meet everyone and interact! Really great energy. 

KEEP DOING: Meet ups, the booth, videos and comms material. 
Big one: having the meet up AFTER the maintainer talk where possible! It meant we could tell people to meet us later that day in x location which was awesome.

MORE OF: 

START DOING: from comms, potentially photos on social media as we go as well as in the slack!

STOP DOING: 

LESS OF:

IDEAS: Add an environmental sustainability track to sched. This is something I brought up before (and would make our lives easier). Unsure what we need to do!

**Comment by leonardpahlke** [comment]
related #266
