### ISSUE TITLE
[Action] Discuss TAG ENV at Open Source Summit EU in Vienna

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#369]
The next Open Source Software Summit in Europe will take place in September (16-18 SEPTEMBER 2024
VIENNA, AUSTRIA). A few people from TAG have attended the conference in recent years. I expect a few will be there this year as well. It would be great to get the TAG people together at this event and represent TAG at the conference. 

The OSS could serve as a milestone for the WG Green Reviews and overall TAG efforts (cc @catblade @mkorbi @guidemetothemoon). Depending on how many TAG Leads and TAG WG Leads attend the conference, we could also have some sort of off-site event. 

* https://events.linuxfoundation.org/open-source-summit-europe/

cc @patricia-cahill @claire-fletcher 
cc @nikimanoledaki @AntonioDiTuri

**Comment by ADiTuri** [comment]
Hi Leo! I will be there! It would be amazing to organize some off-site event the weekend before 14-15, maybe somewhere in the nature close by?

**Comment by claire-fletcher** [comment]
Are enough people going to have a meet up? Otherwise this might be unfortunately a closed issue as it is so close now.
