### ISSUE TITLE
[Action] Project Green Scraper - Update GitHub Actions Workflow implementation to publish PR for changes

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#402]
### Description

Currently the implementation for the Green Scraper GH workflow is to push any changes directly to main branch.
We need to change it to publish a pull request with changes instead so that we can have more control and validate the changes being done to the events page.

### Outcome

GH workflow for Green Scraper project will create pull requests with changes instead of pushing directly to main branch when triggered.

### To-Do

- [ ] Update workflow implementation in https://github.com/cncf-tags/tag-env-tooling/blob/main/.github/workflows/green-talks-scraper.yml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Al-HusseinHameedJasim** [comment]
As discussed in the project meeting, I would like to look into this.

**Comment by guidemetothemoon** [comment]
Thank you, @Al-HusseinHameedJasim !

**Comment by Al-HusseinHameedJasim** [comment]
I have created a [PR](https://github.com/cncf-tags/tag-env-tooling/pull/6) to update the workflow.

**Comment by guidemetothemoon** [comment]
Looks great, thanks @Al-HusseinHameedJasim ! I reviewed and merged the PR so we can close this item. Can open a new one if any issues during testing pop up.
