### ISSUE TITLE
Logo Options for TAG

### ISSUE THREAD

**Issue by amye** [cncf/tag-env-sustainability#41]
Adding a PDF with possible design choices.
[tag-env-sus-logos_v3.pdf](https://github.com/cncf/tag-env-sustainability/files/9880168/tag-env-sus-logos_v3.pdf)

Two options: 
We can choose one of these!

or
We can ask for another set of choices based on group feedback.

**Comment by amye** [comment]
<img width="730" alt="tag-env-sus-logos_v3" src="https://user-images.githubusercontent.com/107161/198309646-28ac1821-2c60-4f98-844a-999ad8967087.png">
PNG for clarity

**Comment by leonardpahlke** [comment]
Awesome!!  I will add this topic for discussion to our tag meeting next week :)

cc @mkorbi @catblade

**Comment by mkorbi** [comment]
thank you @amye and thank you to the designer :) 
I love that whale! +1 on Leo

**Comment by tomkerkhove** [comment]
I love the whale one!

**Comment by agardnerIT** [comment]
Whale with the world gets my vote ❤️

**Comment by williamcaban** [comment]
The last one on the top is too close to ODIM Project (https://odim.io/)

**Comment by catblade** [comment]
My favorite is top left (domain dolphin fish?), but I like simple things.

**Comment by wangchen615** [comment]
+1 for the first one from left on the third row.

**Comment by mkorbi** [comment]
@amye I would have a picky detail request on the whale: could the artist invert the globe, it feels wrong having europe coming in from the left. So then basically there would be NA on the head of the whale and Europe on the tail

**Comment by tomkerkhove** [comment]
Well spotted - The map is also mirrored which feels odd.

**Comment by rootfs** [comment]
@amye does CNCF have copyright on all the artworks?

**Comment by mkorbi** [comment]
@rootfs https://www.linuxfoundation.org/legal/trademark-usage

**Comment by leonardpahlke** [comment]
whale +1 (and +1 for the small globe fix in the logo that have been pointed out before 🙂)

**Comment by catblade** [comment]
I am going to request more unusual sea creatures.  I feel the whale is over-used, and would like us to be easily distinguished from other efforts.  @amye  is it possible to get a few more designs?

**Comment by tomkerkhove** [comment]
Too bad the whale 🐳 is gone, I'd vote for the sea lion

**Comment by rootfs** [comment]
For better addressability, I added coordinates to the logos.

I vote D4

**Comment by rootfs** [comment]
![image](https://user-images.githubusercontent.com/7062400/204366685-4f08b6fe-e9b7-4c8e-bb7c-a3b068eebf24.png)

For better addressability, I added coordinates to the logos.

I vote D4

**Comment by catblade** [comment]
These are fantastic, @amye.  I can't seem to make a choice today... I'm really liking A4, D4, and C3.  All are unique and distinct.

**Comment by leonardpahlke** [comment]
Hi everyone, we now have a number of great logo options to choose from for our TAG! We have created a ballot where multiple suggestions can be submitted :slightly_smiling_face:. You can compare the choices on the ballot with the reference image :blush:
We will close the voting next week Wednesday at our TAG meeting!
Ballot link: https://www.rcv123.org/ballot/jd4QVE6RL2PojzuYjrihb5
![CNCF-TAG-ENV-LOGO-OPTIONS](https://user-images.githubusercontent.com/58054077/204383915-a0e99b39-abb8-4b3f-809b-438986c87e5d.png)

**Comment by by-d-sign** [comment]
Hi, I may have missed a memo. Is there a reason why they are mostly maritime themed? I wouldn't want any confusion over what it is that we actually do especially, if we use this logo to represent us outside of the CNCF.

**Comment by catblade** [comment]
I had asked for weird sea creatures, because our oceans are so much of the planet and people liked the whale.

**Comment by leonardpahlke** [comment]
The vote ended! B1, the Whale 🐋 is the winner 🎉 (see [results](https://www.rcv123.org/results/jd4QVE6RL2PojzuYjrihb5/254hZLFDFQYvopnFcC2uu6)) 🙂

**Comment by caradelia** [comment]
> /cc @amye do we will get the logo files, SVG, png etc? :)

Do we have these yet @amye or @mkorbi? I need as am working on the website.

**Comment by leonardpahlke** [comment]
https://github.com/cncf/artwork/pull/390 Logos have been added to the artworks Repo :)
