### ISSUE TITLE
[Action] Onboard Saiyam Pathak as TAG ENV TL

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#421]
### Description

@saiyam1814 has been approved as TAG ENV TL https://github.com/cncf/toc/issues/1322. 

### Outcome

@saiyam1814 needs to be added to groups, websites and chats. 

### To-Do

- [ ] 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leonardpahlke** [comment]
@saiyam1814 i've added you to the TAG ENV shared cal. Edit rights. https://calendar.google.com/calendar/embed?src=72e93a411f02e5664bb4485c04311b83dae6a62574e4ab882a1ccf8526aa9bf1%40group.calendar.google.com

**Comment by leonardpahlke** [comment]
@saiyam1814 i've added you to the shared (public) TAG ENV gdrive https://drive.google.com/drive/folders/1OD491XwHhpRrJSuh3leQrcNhYyN3CDdj?usp=sharing

**Comment by leonardpahlke** [comment]
@saiyam1814 I've added you to the LinkedIn group as content admin https://www.linkedin.com/company/cncf-tag-environmental-sustainability/ (@claire-fletcher added you too 😉)

**Comment by leonardpahlke** [comment]
Added a CNCF service desk ticket to add @saiyam1814 to the https://lists.cncf.io/g/cncf-tagenv-leads group

**Comment by leonardpahlke** [comment]
@saiyam1814 I've added you to the TAG ENV YouTube channel https://www.youtube.com/channel/UCMOopJuyyIWB8vXGct1ffNw (@guidemetothemoon added you too 😄)

**Comment by leonardpahlke** [comment]
@saiyam1814 I've added you to the TAG-ENV Leads and TAG-ENV WG Leads channel in slack.

**Comment by leonardpahlke** [comment]
@guidemetothemoon could you share the 1password vault with @saiyam1814 - 🙌

**Comment by leonardpahlke** [comment]
@saiyam1814 I've shared you the zoom meeting host guide & host key. See playbook https://github.com/cncf/tag-env-sustainability/blob/main/governance/meeting-host-playbook.md

**Comment by guidemetothemoon** [comment]
@saiyam1814 please send me an email address that I can share 1Password access with😊

**Comment by saiyam1814** [comment]
> @saiyam1814 please send me an email address that I can share 1Password access with😊

saiyam911@gmail.com

**Comment by guidemetothemoon** [comment]
@saiyam1814 thanks! You should have received an invitation to join 1Password. Please let me know once you did that so that I can verify your permissions.

**Comment by saiyam1814** [comment]
> @saiyam1814 thanks! You should have received an invitation to join 1Password. Please let me know once you did that so that I can verify your permissions.

I did receive and have signed up

**Comment by leonardpahlke** [comment]
@saiyam1814 is onboarded 🎉 . closing the issue.
