### ISSUE TITLE
[Suggestion] Prepare TAG Events for KubeCon / CloudNativeCon EU 2023

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#43]
KubCon / CloudNativeCon NA just ended last week, but we'll have it again in not too long, in April [2023 in Amsterdam](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/). Planning meetings and events takes a lot of time and coordination. So it would be good to start the process early to get a team together, brainstorm ideas for the event and coordinate.

Proposed next steps:
1. Ask for folks that are interested in helping here
2. Brainstorm and discuss ideas
3. Planning & coordination

/cc @catblade @mkorbi

**Comment by mkorbi** [comment]
fyi I send the other day an email to the CNCF event team asking for a project meeting timeslot

**Comment by mkorbi** [comment]
fyi @caradelia the project meeting benefits will be published in January, from that time on we are allowed to apply for a project meeting. First come first serve.

**Comment by berryq460** [comment]
As mentioned today in the meeting Feb.1, I propose we leverage the audience at Kubecon to build relationships with future potential members while accomplishing our mission to educate the open source community. We can accomplish this by:

-  Hosting at least 2 sustainability meetups at different times led by our members to discuss their interests and/or pain points around sustainability within their org today ( I can lead 1)
- Formalizing a new survey to get users feedback - can include a QR code at end of presentation for live surveying
-  Educating new members about the mission of this group, broader sustainability principles and evangelizing our group- we can all wear our logo on t shirts so we increase brand awareness and stir curiosity
- Propose we have formal website with a blog by Kubecon so we can point interested parties to at our event

**Comment by nikimanoledaki** [comment]
As mentioned in today's meeting, we could add sustainability-related KubeCon EU '23 talks here in the comments.

* @leonardpahlke - [The State of Green Software + Cloud Native - Leonard Vincent Simon Pahlke, Liquid Reply](https://kccnceu2023.sched.com/event/1Hzd3/the-state-of-green-software-cloud-native-leonard-vincent-simon-pahlke-liquid-reply)

**Comment by by-d-sign** [comment]
Since KubeCon 2023 in Amsterdam is approaching rapidly. I want to follow up on the suggestions from @berryq460. Did we make any progress here?
If yes, where can that progress be found?
If no, do we still want to do any of this?

I am very much in favor of having one or two meetups. They do not need to be fancy maybe just getting a drink or something to eat while talking about what’s on people’s minds.
I would also like another survey, which this time does not focus to much on data centers but more on the state of software/cloud-native development?
Please let me know how you would like to organize/push any of these topics.

**Comment by leonardpahlke** [comment]
hey, we will have a meetup on Tuesday https://sched.co/1JWOX and another one after the TAG talk on Friday. I created a document to brainstorm ideas https://docs.google.com/document/d/1ESxvXcSiorwi_Zh1WXuVmHJcSlR5aJQbCYfh11xRXqw/edit#. 

> They do not need to be fancy maybe just getting a drink or something to eat while talking about what’s on people’s minds

I think we should get a agenda set out to make use of the meetup.

> I would also like another survey, which this time does not focus to much on data centers but more on the state of software/cloud-native development?

You are very welcome to start with something in this direction 👍. Let me know if you need something to get this started.

**Comment by by-d-sign** [comment]
Do we have a room/space for the meeting on Friday?

**Comment by leonardpahlke** [comment]
> Do we have a room/space for the meeting on Friday?

Not yet. We still have to organize something. If you want, you can do the organizational part.

**Comment by berryq460** [comment]
I will let you guys run with my idea proposed above as I cannot attend this year due to company budget. Would love to hear what the outcome was. Have fun!

**Comment by leonardpahlke** [comment]
It was great in Amsterdam! See you all at the next KCCN :)
