### ISSUE TITLE
[Action] WG Comms Second Chair

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#431]
### Description

The WG Comms has recently had both chairs step down and a new chair (myself) step in. This now leaves us with an open spot which we will need filling. We need to see who might be interested and a good fit for this!  

Lets use this issue to track finding someone and open a separate nomination issue when we do. Until then the other WG leads will assist with the work!

### Outcome

Second WG Comms Chair

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by by-d-sign** [comment]
Hi @claire-fletcher, unless the position has already been filled, I'd like to throw my hat in the ring.

**Comment by claire-fletcher** [comment]
Hi @by-d-sign it hasn't and that would be amazing!

**Comment by ams0** [comment]
I want to step up my contribution too, so consider me for the co-chairship!

**Comment by Nancy-Chauhan** [comment]
I would love to contribute here 💚

**Comment by vallss** [comment]
Hi! I've been thinking about this a lot lately and I would like to try and volunteer for this role too!

**Comment by dipankardas011** [comment]
Hi I would also want to give it chance ;)

**Comment by ams0** [comment]
@claire-fletcher when will this nomination phase start? Eager to help (apologies I missed the meeting this week, looking forward to the recordig when it's posted)

**Comment by claire-fletcher** [comment]
We will be closing this issue now that we have gone through the WG Chair election process. However, please still take note of Leo's post about leadership roles throughout the TAG!
