### ISSUE TITLE
APAC meeting Discussion issue - 9th July 2024 

### ISSUE THREAD

**Issue by saiyam1814** [cncf/tag-env-sustainability#448]
### Description

APAC meeting Discussion issue - 9th July 2024 

### Outcome

to get discussion points 

### To-Do

- [ ] ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamYuan1990** [comment]
Some updates:
- for reuse with kepler CI, we had a discussion in slack, but it seems kepler's CI is on fundamental level, progress level... some difference with TAG's CI, let's see how to reuse them in the feature?
- for sustainable week's meet up in China, the LF member is on vacation in recent, will have a talk with him and update later. Current plan is with https://github.com/cncf/tag-env-sustainability/pull/444 published on local social network.
have another blog locally:
 1. Introduce sustainable week, and announce APAC meeting.
 2. Introduce sustainable week meet up. 
 3. Call for sponsors and volunteers for sustainable week meet up in China.

**Comment by saiyam1814** [comment]
Completed
