### ISSUE TITLE
[Tracking] TAG Documentation Update: TAG Environmental Sustainability

### ISSUE THREAD

**Issue by riaankleinhans** [cncf/tag-env-sustainability#457]
### Description

This issue supports updating the TAG README, Charter and moving documents to the TAG’s Gdrive. The work will be tracked in the TOC Tracking issue #1366.

### Outcome

Updated document as per TOC guidelines

### To-Do

The following points should be addressed:

- PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
- PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/tree/main/tags/tag-charters)
- Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leonardpahlke** [comment]
> Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG. The aim of this update is to ensure no documents get lost in private or company accounts.

@riaankleinhans we currently have the [APAC meeting notes document](https://github.com/cncf/tag-env-sustainability/blob/c5b48fdb8295796d6641a72f9d141f87c83b57bc/meeting-notes-apac.md) in the repo. Folks in China are unable to access all (or most) google products. They are unable to use gdrive, gdocs etc. If you recommend a different approach- please let us know. Maybe LFX could help- not sure.

**Comment by leonardpahlke** [comment]
toc tag charter template link: https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md

**Comment by riaankleinhans** [comment]
> Folks in China are unable to access all (or most) google products. They are unable to use gdrive, gdocs etc. If you recommend a different approach- please let us know. Maybe LFX could help- not sure.

@leonardpahlke on docs LFX does not have a solutions. I am a fan of managing things in GH.
If GDoc is a problem, and the community have the GH skills it make sense to switch to GH with meeting docs.

**Comment by leonardpahlke** [comment]
Our drive is managed by CNCF. So we are good 👍

**Comment by guidemetothemoon** [comment]
All tasks on the list are now completed so closing this issue.
