### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Amsterdam

### ISSUE THREAD

**Issue by JulieChenadec** [cncf/tag-env-sustainability#462]
### Description

* **Location/Region:** Amsterdam, Notherlands
* **Organizers:** @ams0 @JulieChenadec @wilco @pavel
* **Sponsors:** tbd
* **Date:** 10th October 2024
* **Event link:** https://www.meetup.com/dutch-kubernetes-meetup/events/301418005/

### Details

We'll have a full half-day of programs, workshops, talks, and plenty of time and space to connect and brainstorm on how to get better sustainability out of cloud native software.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [X] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [X] Find a location for the event.
- [X] Set a date for the event.
- [X] Announce the event.
- [x] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mijndert** [comment]
@JulieChenadec getting a 404 on the linked event page.

**Comment by ams0** [comment]
It's a draft at the moment, will publish and make one event on community.cncf.io as well this week!

**Comment by JulieChenadec** [comment]
Thanks for jumping in, Alessandro! Indeed it will be published soon @mijndert :)

**Comment by Nancy-Chauhan** [comment]
Hello @JulieChenadec @ams0 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything.

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
