### ISSUE TITLE
APAC meeting Discussion issue - 6th August 2024

### ISSUE THREAD

**Issue by saiyam1814** [cncf/tag-env-sustainability#474]
### Description

APAC meeting Discussion issue - 6th August 2024

### Outcome

APAC meeting Discussion issue - 6th August 2024

### To-Do

- [ ] ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamYuan1990** [comment]
for sustainable week in China, we already start call for volunteers and sponsor process/progress.... waiting...
as kubecon China in Aug, the plan will come up after kubecon China.
and also need to check with global sustainable week prepare session information.
if I got time.
busy with personal issue....
