### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Kuala Lumpur

### ISSUE THREAD

**Issue by mageshwaransekar** [cncf/tag-env-sustainability#475]
### Description

* **Location/Region:** Asia, MY
* **Hosting Local Community**: [Cloud Native Kuala Lumpur](https://community.cncf.io/cloud-native-kuala-lumpur)
* **Organizers:** Mageshwaran Sekar (@mageshwaransekar), Khairul Anuar, Ahmed Zidan (@ahmedzidan)
* **Sponsors:**
  * Venue Sponsor: Microsoft Malaysia
  * Food Sponsor: [MoneyLion](https://www.moneylion.com)

* **Date:** 21 October 2024
* **Event link**:
  * [Bevy](https://community.cncf.io/events/details/cncf-cloud-native-kuala-lumpur-presents-sustainability-cloud-native-kuala-lumpur-meetup-october-2024/)
  * [meetup.com](https://www.meetup.com/cloud-native-kuala-lumpur/events/303722451)
* **Call for Speakers:** [sessionize.com](https://sessionize.com/cloud-native-kuala-lumpur)

### Details

We plan to run Cloud Native Sustainability Week in Kuala Lumpur (Malaysia) in 2024 as a regular (3 hours) meetup

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [X] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [X] Find a sponsor for the event.
- [X] Find a location for the event.
- [X] Set a date for the event.
- [X] Announce the event.
- [x] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mageshwaransekar** [comment]
Added PR #484

**Comment by Nancy-Chauhan** [comment]
Hello @mageshwaransekar 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything. It would also be great if you could provide us with updates in your TO-DO section.

**Comment by JulieChenadec** [comment]
Hi @mageshwaransekar As Nancy pointed out, do you need any support?

**Comment by mageshwaransekar** [comment]
Hi @Nancy-Chauhan @JulieChenadec - From our side, we have already sorted out the venue and speakers. Only thing still ongoing is the look out for food sponsor.

**Comment by vallss** [comment]
Hi! Just a reminder to submit all the speakers and organizers' information for Credly badges using this form https://forms.gle/KHizxY47h3ynEBUL9


Edit: all the information have been submitted

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
