### ISSUE TITLE
[Tracking] Landscape Document

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#48]
#### Description

This is the tracking item for the landscape document and the follow-up issue for this discussion: https://github.com/cncf/tag-env-sustainability/discussions/22

**Document**: https://github.com/catblade/wg-env-sustainability/blob/landscape_document/documentation/WhitePapers/SustainabilityUseCasesAndLandscape2022.md

**Comment by catblade** [comment]
@leonardpahlke  as people are already participating re github and hackmd, I would like to leave it where it is.  We can move the next one.

**Comment by leonardpahlke** [comment]
@catblade ok, sounds good to me. I will delete the google docs file.

> We can move the next one.

Yes

**Comment by catblade** [comment]
Are we ready to close this?

**Comment by leonardpahlke** [comment]
Yes as we have the first version merged
