### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Oslo

### ISSUE THREAD

**Issue by guidemetothemoon** [cncf/tag-env-sustainability#487]
### Description

* **Location/Region:** Oslo, Norway
* **Organizers:** @guidemetothemoon @xamebax as part of the [Green Software - Oslo](https://www.meetup.com/gsf-oslo) meetup group
* **Sponsors:** [Computas](https://computas.com/en/)
* **Date:** 9th October 2024
* **Event link:** [Green Software Foundation Oslo - October Meetup [In-Person]](https://www.meetup.com/gsf-oslo/events/303318869)

### Details

Bring together community members who are interested in the topic of environmental sustainability in tech, create a forum for discussions and spread knowledge and learnings around the topic, adoption of tools, patterns and routines, etc.

The plan is to have 2-3 speakers for the event + introduction to the TAG ENV by the organizers.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [x] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [X] Find a sponsor for the event.
- [X] Find a location for the event.
- [X] Set a date for the event.
- [x] Announce the event.
- [x] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nancy-Chauhan** [comment]
Hello  @guidemetothemoon 

I hope you're doing well. With just a few weeks left, I wanted to check in and see if you need any help with anything.

**Comment by guidemetothemoon** [comment]
The last task remaining for our meetup is to upload recordings of the talks. Our meetup groups doesn't have our own YouTube channel. Recordings are available in the "Post-Event Local Meetup" folder for Oslo, Norway in the TAG ENV Google drive: https://drive.google.com/drive/folders/1w_8hQGvlBTD-gMubN0ajuc3J-yJSXzCS?usp=drive_link

@claire-fletcher @Nancy-Chauhan @vallss can local meetup recordings be uploaded to the TAG ENV YouTube channel, for example to a Cloud Native Sustainability Week 2024 playlist?

@xamebax @leonardpahlke FYI.

**Comment by guidemetothemoon** [comment]
All recordings from Oslo meetup are now added and published in the Cloud Native Sustainability Week 2024 playlist: https://youtube.com/playlist?list=PL_3_oSSuNpD7I2OHgywlAuKnJf700wcXH&si=d_E2diGJst8L3ONm

As far as I can see no more action points left for the organizers of this local meetup organizers so the issue is ready to be closed😊

**Comment by guidemetothemoon** [comment]
I don't think that we will be writing any blog post about this specific meetup but we will probably create some social media posts where the meetup and session recordings, and Cloud Native Sustainability Week will be mentioned☺️ Therefore I'll just close this issue since we have no more items to follow-up.

Thanks for all your support throughout this initiative! Already looking forward to next year💚
