### ISSUE TITLE
[BUG] Geography issue for figure in 2023

### ISSUE THREAD

**Issue by SamYuan1990** [cncf/tag-env-sustainability#492]
### What happened?

A bug happened!
in figure of this blog https://tag-env-sustainability.cncf.io/blog/2024-wrap-up-cloud-native-sustainability-week-2023/
<img width="153" alt="image" src="https://github.com/user-attachments/assets/2fde2ab9-51af-4112-8f68-510d64b73315">

Hainan Province is not marked up correctly.
For more details of hainan(海南), please ref
https://baike.baidu.com/item/%E6%B5%B7%E5%8D%97%E5%B2%9B/179653?fr=ge_ala
https://www.hainan.gov.cn/hainan/mhainan/index_m.shtml
https://baike.baidu.com/item/%E6%B5%B7%E5%8D%97%E7%9C%81/533000?fromtitle=%E6%B5%B7%E5%8D%97&fromid=13346&fr=aladdin

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sunya-ch** [comment]
@SamYuan1990 
I tried making the fix here: https://drive.google.com/file/d/1AUtwdgVMhX6uDO45PJJ9_VvpmMpmBhWg/view
Could you please confirm? If this looks fine to you, I will proceed updating the image and push a PR to update the website.

cc: @Nancy-Chauhan

**Comment by guidemetothemoon** [comment]
@SamYuan1990 this is now fixed and we can close this issue, right?

**Comment by SamYuan1990** [comment]
the PR #498 LGTM, thanks. in recent I am busy with personal issue, sorry for reply late.
