### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 Gurugram

### ISSUE THREAD

**Issue by mounicarajput** [cncf/tag-env-sustainability#506]
### Description

* **Location/Region:** Opstree Solutions
* **Organizers:** Monika Rajput , Ankit Yadav, Pankaj Raghav
* **Sponsors:** Opstree solutions, StackGuardian
* **Date:** 5th October 2024
* **Event link:** [https://community.cncf.io/events/details/cncf-cloud-native-gurugram-presents-sustainable-hacktober/](https://community.cncf.io/events/details/cncf-cloud-native-gurugram-presents-sustainable-hacktober/)

### Details

1. We have 5 talks that will focus on Sustainability.
2. Open discussion among attendees.

### To-Do

- [X] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [X] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [X] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [X] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [X] Find a sponsor for the event.
- [X] Find a location for the event.
- [X] Set a date for the event.
- [X] Announce the event.
- [X] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by saiyam1814** [comment]
Thanks for adding this, we will track this under India. Do you have everything you need form the TAG side?
