### ISSUE TITLE
Nomination Green Reviews WG Tech Lead: Flavia Paganelli

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf/tag-env-sustainability#513]
Dear TAG ENV and Green Reviews WG members,

Flavia has been providing technical guidance in the Green Reviews WG meetings for a long time. She has led the second proposal, consistently breaks ties when the group faces tradeoffs, and drives the project forward in and outside of our meetings. Growing the Green Reviews WG leads helps us to distribute the workload of this demanding yet volunteer-run project. With her leadership, we can make the team more sustainable and set ourselves on the right track to achieve our long-term goals.

I would like to nominate @locomundo for the WG Green Reviews Tech Lead role.

All community members are welcome to vote by commenting on this issue. Votes are non-binding for community members and binding for TAG Chairs & TLs. Please vote (+1/0/-1) by replying to this thread.

As mentioned in the TAG ENV Governance:

> Community nominations will run for at least 2 weeks, with a maximum up to 1 months. The TAG Chairs will take a vote. Upon close of nominations, a decision should be made within the next month.

All the best,
Niki

**Comment by AntonioDiTuri** [comment]
+1

**Comment by vallss** [comment]
+1!

**Comment by guidemetothemoon** [comment]
+1B 😸

**Comment by leonardpahlke** [comment]
+1B

**Comment by saiyam1814** [comment]
+1

**Comment by claire-fletcher** [comment]
+1

**Comment by leonardpahlke** [comment]
Thank you all for voting! The vote passed. Congratulations @locomundo 💚 🎉.

@nikimanoledaki could you update the [green reviews readme](https://github.com/cncf/tag-env-sustainability/tree/main/working-groups/green-reviews), meetings notes & repo documentation- thank you!

**Comment by locomundo** [comment]
Thank you all! 😄
