### ISSUE TITLE
Nomination Communications WG Tech Lead: Valeria Salis

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#520]
Dear TAG ENV and Comms WG members,

The WG is expanding its leadership and is looking of a technical lead. This role will help the chairs to ensure work is being distributed and take on ensuring that all projects under the WG are progressing, particular aspects of which projects and work they will lead will be discussed with the new person.

As such, I would like to nominate @vallss for this role!

Valeria has diligently helped the WG to progress and taken time to help define what we do and how we will do it. She consistently volunteers to help with work and takes time to organise meetings to discuss this. She often takes the initiative and, for instance, has used her design connections to improve our efficiency by creating presentation templates. She is also a large contributor across the TAG to many different projects which will give her useful insight from a communications and sustainability advocacy perspective. Valeria's organisation and dedication to helping makes her a great candidate for this role.

All community members are welcome to vote by leaving a comment on this issue. Votes are non-binding for community members and binding for TAG Chairs & TLs. Please vote (+1/0/-1) by replying to this thread.

As mentioned in the TAG ENV Governance:

> Community nominations will run for at least 2 weeks, with a maximum up to 1 months. The TAG Chairs will take a vote. Upon close of nominations, a decision should be made within the next month.

Thank you for considering my nomination: Valeria Salis.

Claire ✨

**Comment by nikimanoledaki** [comment]
+1 🎉

**Comment by rossf7** [comment]
+1

**Comment by guidemetothemoon** [comment]
+1B😸

**Comment by catblade** [comment]
+1B

**Comment by Ludovik95** [comment]
+1 🌈

**Comment by leonardpahlke** [comment]
+1B

**Comment by akelity** [comment]
+1

I had the opportunity to work with Valeria for the Sustainability Week in Milan, and without her (and @Ludovik95) our events wouldn't have taken place. So I'm writing +1, but I mean +infinity.

**Comment by locomundo** [comment]
+1 !

**Comment by leonardpahlke** [comment]
Thank you all for voting! The vote passed. Congratulations @vallss 💚 🎉.

@claire-fletcher could you update the website, the [comms readme](https://github.com/cncf/tag-env-sustainability/blob/main/working-groups/communications/README.md) & meeting notes- thank you!

**Comment by vallss** [comment]
Thank you everyone! 💚
