### ISSUE TITLE
WG Comms sustainability week presentation

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#521]
As part of sustainability week we will present about WG comms.

To Do:

- [x] Create plan
- [x] Create slides
- [x] Finalise slides

**Comment by vallss** [comment]
Just to have all the doc here too: 
- [link to presentation](https://docs.google.com/presentation/d/1zHzzWQOIgq76TzQg3Hv94VeIj7DUsZHqCTCCHUj6o5Q/edit?usp=sharing)
- [brainstorming/notes](https://docs.google.com/document/d/1BY-7i7RJ2qQ9qGY8EZ8JNIUNNaFlAMH-0lJiQAT0gB8/edit#heading=h.px1q1bndlq6o)

**Comment by vallss** [comment]
We finalised the slides! Also we have a new great presentation and template for Comms (future _WG Sustainability Advocacy_!).

We can close this issue 😄
