### ISSUE TITLE
[Tracking] Cloud Native Sustainability Week 2024 University of Calgary

### ISSUE THREAD

**Issue by Marvelrex** [cncf/tag-env-sustainability#535]
### Description

* **Location/Region:** Univeristy of Calgary ICT building 516, Zoom
* **Organizers:** Jialin Yang, Zainab Saad
* **Sponsors:** University of Calgary
* **Date:** Oct th23 17:30-19:00
* **Event link:** [Zoom Link](https://ucalgary.zoom.us/j/98863965597?pwd=kgvos8TwYtbBdheEOh9gN07zk2uGco.1)

### Details

My name is Jialin Yang, and I am a master's student under Dr. Steve Drew at the University of Calgary. We are hosting the Cloud Native Sustainability Meetup at the University of Calgary, where I will present an overview of the Kubernetes Scheduler from both industrial and academic perspectives, highlighting its potential to reduce carbon emissions and enhance energy efficiency. Zainab Saad will share her work on using federated learning to predict carbon emissions. Looking for anyone interested to join the discussion or ampify your voice!

### To-Do

- [x] Review the [Meetup Organizer Guide](https://docs.google.com/document/d/1xfUqxt0EeMhrsg8h5p_cAJ1ZHzWryrIywue53rVRFJw/edit?usp=sharing) for onboarding.
- [x] Check the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/).
- [x] Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example [PR](https://github.com/cncf/tag-env-sustainability/pull/170).
- [x] Join one of the TAG ENV Sustainability Week Syncs to talk about your event.
- [x] Find a sponsor for the event.
- [x] Find a location for the event.
- [x] Set a date for the event.
- [x] Announce the event.
- [x] Reach out to the Cloud Native Sustainability Week Organizer team to promote the event.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vallss** [comment]
Hi @Marvelrex, can you please open a PR as suggested in point three of the To Do list?

> Create a PR to update the Meetup's table on the [website](https://tag-env-sustainability.cncf.io/events/cloud-native-sustainability-week/). Example https://github.com/cncf/tag-env-sustainability/pull/170. 

This way we can track and show the event along with all the others on the Website. 

If you need help with this, feel free to ask!

**Comment by Marvelrex** [comment]
Hi @vallss, thanks for letting me know! I have created a PR for the Meetup table.
[PR](https://github.com/cncf/tag-env-sustainability/pull/546)

**Comment by vallss** [comment]
Closing this since all the main activities were completed. Thanks to everyone who made this local event possible and contributed! 🔝
