### ISSUE TITLE
[BUG] Meeting recordings are not uploaded to YouTube

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf/tag-env-sustainability#545]
### What happened?

@locomundo and I are working on the slides for the Green Reviews intro for the mini conference. We just noticed that the meeting recordings have not been uploaded to the YouTube channel since June. 🙊 https://www.youtube.com/@CNCFEnvTAG/videos

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nikimanoledaki** [comment]
FYI @cncf/tag-leads

**Comment by nikimanoledaki** [comment]
FYI @cncf/tag-env-sustainability

**Comment by claire-fletcher** [comment]
Do you have admin access? It is likely that they are there but haven't had their thumbnail added and status set to public. One of the comms group action points for our roadmap planning will be a potential rota across the leads to ensure this gets done.

**Comment by vallss** [comment]
Should we add the wg-comms label so we can talk about this issue later today?

**Comment by claire-fletcher** [comment]
Yes lets. It has come up before (during roles review) but became too much for me to monitor on my own. Definitely worth floating the rota idea/some sort of check-in.

**Comment by claire-fletcher** [comment]
We've discussed this and we are going to take the opportunity to make a document explaining how, some new thumbnails, upload this all to the drive and then have chairs of the meetings be in charge of ensuring each of the meetings they run is correctly uploaded.

**Comment by claire-fletcher** [comment]
I have created a document: https://docs.google.com/document/d/1PmhITy-7zpJxgW2iVGgwuF2ro5vgVyv5fMYqpsblQWc/edit#heading=h.iauc1y6zsy7a 

We are also going to improve the thumbnails

**Comment by leonardpahlke** [comment]
👍, good to talk about this. +1, that the chairs (tag/wg) are responsible for the meeting upload.

**Comment by leonardpahlke** [comment]
maybe there is a way to automate it better. If smb has any ideas.. 💡 

There is the option to create multiple zoom meeting rooms (so there is a link for each of the WGs, for the TAG and maybe additional ones). In this case the zappier automisatipn could set title, playlist, description, etc. and also set the video live.

Downsides (& reasons why we are not doing this approach):

1. its easier with just one meeting link. You don't need to look it up.
2. we need to regularly create new meeting rooms in zoom to cover varring meeting 
3. zappier free tier will be exceeded, so we would need to pay for a subscription.

**Comment by leonardpahlke** [comment]
That's a good point @riaankleinhans. I haven't checked out all the LFX functions recently. There might be smth we could use!

**Comment by SamYuan1990** [comment]
@leonardpahlke , I have a question, as in China we can't access YouTube or google drive, hence is there any chance for me to get a copy of the recordings and upload them to Chinese social media?

**Comment by riaankleinhans** [comment]
> [@leonardpahlke](https://github.com/leonardpahlke) , I have a question, as in China we can't access YouTube or google drive, hence is there any chance for me to get a copy of the recordings and upload them to Chinese social media?

@SamYuan1990 can you view this recording: (It is from another TAG in the LFX system)
https://zoom.us/rec/play/Vb8Ar6mrk-P7_HK6lKa05r6HVJbzdTb34xgeCaqF3vY76XjETdMcfjgurKPQmcJaFf81eJb-Pw8mYv4.PV7DWPM7wE2A-lAt?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FuVMsYigixfGh5Dn3M7of8M2Hah3-ytlgJhbmb3PXiHVDff3zqqWIVSn66hcGr2nW.k5FE65bI6bbi6Clu

**Comment by SamYuan1990** [comment]
> > [@leonardpahlke](https://github.com/leonardpahlke) , I have a question, as in China we can't access YouTube or google drive, hence is there any chance for me to get a copy of the recordings and upload them to Chinese social media?
> 
> [@SamYuan1990](https://github.com/SamYuan1990) can you view this recording: (It is from another TAG in the LFX system) https://zoom.us/rec/play/Vb8Ar6mrk-P7_HK6lKa05r6HVJbzdTb34xgeCaqF3vY76XjETdMcfjgurKPQmcJaFf81eJb-Pw8mYv4.PV7DWPM7wE2A-lAt?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FuVMsYigixfGh5Dn3M7of8M2Hah3-ytlgJhbmb3PXiHVDff3zqqWIVSn66hcGr2nW.k5FE65bI6bbi6Clu

I can access this link and download the files. Great

**Comment by riaankleinhans** [comment]
Great, glad that work for you.
If this TAG choose to move to LFX/Zoom meetings the recordings would be available on the community calendar and can be view anywhere in the world (specifically China) 
The LFX/Zoom instance also do not need signing in, so the meetings also work in China. 
Some TAGs moved their APAC meetings to LFX/Zoom for this reason.

**Comment by SamYuan1990** [comment]
> Great, glad that work for you. If this TAG choose to move to LFX/Zoom meetings the recordings would be available on the community calendar and can be view anywhere in the world (specifically China) The LFX/Zoom instance also do not need signing in, so the meetings also work in China. Some TAGs moved their APAC meetings to LFX/Zoom for this reason.

well, where can I find all the recordings via a LFX/Zoom link? so that I can regularly/schedule to make the content into social media in China.

**Comment by saiyam1814** [comment]
> > > Great, glad that work for you. If this TAG choose to move to LFX/Zoom meetings the recordings would be available on the community calendar and can be view anywhere in the world (specifically China) The LFX/Zoom instance also do not need signing in, so the meetings also work in China. Some TAGs moved their APAC meetings to LFX/Zoom for this reason.
> > 
> > 
> > well, where can I find all the recordings via a LFX/Zoom link? so that I can regularly/schedule to make the content into social media in China.
> 
> The TAG are not using LFX/Zoom yet. If they switch, it would be available going forward.

Hello @riaankleinhans how can we request for LFX/Zoom? We are ready to switch.

**Comment by leonardpahlke** [comment]
Kristina updated the documentation last week regarding uploading videos to YT https://github.com/cncf/tag-env-sustainability/pull/556.
