### ISSUE TITLE
[Tracking] FOSDEM conference Feb 4&5

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#56]
Hey all, there is an opportunity at the [FOSDEM2023](https://fosdem.org/2023/) in Brussels early next year to push sustainability in the community. Some folks from the conference and LF contacted us if we would be interested in participating. They are planning a DevRoom around energy ⚡ .

> FOSDEM has the concept of 'devrooms' to group content. It literally is a physical room and thereby can be equated to a track. And the context helps to group content and people together and foster a sense of community and the relations that come of it.
Together with some other people from LF Energy we have developed the idea to host a devroom on the topic of Energy at FOSDEM next year. The main goal is to grow a community that is wider in in scope than the LF groups and has attendees outside of industry and academia. The have been presentations on energy related topics on community conferences in the past, I even held one myself, but by having a devroom we would get some synergy going and really set the topic on the map by having a label for it.
Now more than ever energy is an important topic to discuss as the war in Ukraine and climate issues are driving up energy prices. The need for action and solutions is greater than ever.
 
> At this moment we're with about 7 people involved in the organization. Currently we're preparing a proposal for the DevRoom to submit to the FOSDEM organizers when the Call for Devroom proposals is announced. As there are more devroom proposals than physical space, there is no guarantee the devroom will make it and we have to make the proposal as interesting as possible.
Here are some more details on the devroom and what is needed in terms of organization https://fosdem.org/2022/manuals/program/devroom/

Feel free to drop a comment if you are interested in participating, maybe we can organize something!

cc @nikimanoledaki (Marlow mention you might be interested 🙂 )

**Comment by leonardpahlke** [comment]
I dont know yet if I have time on the 4th and 5th.

**Comment by mkorbi** [comment]
I can help with the talk, not sure if I could make it to Brussels

**Comment by agardnerIT** [comment]
Let me know how I can help. I can discuss with my employer potentially too. Happy to have a call to discuss.

**Comment by davidebianchi** [comment]
If I can help, let me know. I can have a talk about kube-green on the sustainability topic!
