### ISSUE TITLE
[Action] Adjust website calendar

### ISSUE THREAD

**Issue by claire-fletcher** [cncf/tag-env-sustainability#562]
### Description

The calendar on the website points people towards cncf calendar and the tag google calendar. We should make it more clear that we use the google calendar and that the CNCF one may be out of date due to regular updates.

### Outcome

Obvious calendar links!

### To-Do

- [ ] ...

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Comments

@vallss has agreed to look at this

**Comment by vallss** [comment]
@claire-fletcher do we prefer to remove entirely the CNCF calendar reference or do we keep it but add a disclaimer about it being probably out of date? If the CNCF calendar is not needed on the TAG Env website we could remove it to avoid any further information that could be confusing.
