### ISSUE TITLE
[Presentation] kube-green: increase cloud software sustainability reducing CO2 footprint

### ISSUE THREAD

**Issue by davidebianchi** [cncf/tag-env-sustainability#57]
#### Title

[kube-green](https://kube-green.dev): increase cloud software sustainability reducing CO2 footprint

#### Speaker

[davidebianchi](https://github.com/davidebianchi)

#### Description

The software development has an impact on the environment.

The developers who created software generally don't think they have an important impact on the world climate.
Now, however, it's the time to think about the future.

For this reason I realised [kube-green](https://kube-green.dev), an open source Kubernetes controller on GitHub with the aim to reduce the carbon footprint of Cloud Native application.

In this presentation, I will explain how kube-green works and how it can help us to reduce our impact on the environment.

### Time

Around 30 minutes.

### Availability

From the 1st of february each day it's fine.

**Comment by mkorbi** [comment]
Hey @davidebianchi 
thank you for your submission! We will let you know when will be the next meeting we can welcome your presentation.

**Comment by davidebianchi** [comment]
Hi @leonardpahlke
Great! Yes, for me it's ok on 15 March at 5pm. Thank you!

**Comment by leonardpahlke** [comment]
Thanks @davidebianchi for the presentation!
