### ISSUE TITLE
[Suggestion] Collect tech companies guides on their green guidlines

### ISSUE THREAD

**Issue by mkorbi** [cncf/tag-env-sustainability#84]
> This proposal was brainstormed during the TAG project meeting at KubeCon EU in Amsterdam

#### Description

The idea is pretty simple: We call for contribution and ask all "big tech" companies for their green IT guidelines or paragraphs within their Sustainability Guidelines.

From the response, we will draft a template that others can use.

#### Scope

The effort behind it will be large as we have to track the outreach and responses. Putting everything together and so on.

#### Additional info and comments

We need to discuss if this is still within our scope. 

No further deep thoughts are made on this, should be handled with care. 

P.S.: I'm just the facilitator of this suggestion.

**Comment by mkorbi** [comment]
I think this would fit into the Comms WG
WDYT @caradelia ?

**Comment by leonardpahlke** [comment]
I will close this since we are starting a project with this purpose #361
