### ISSUE TITLE
[Blog] Intro TAG & Kubecon EU wrap-up

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#85]
Writing a blog post about the TAG ENV and what environmental sustainability related happened at Kubecon EU

This blog post should be a joined effort.
I would like to invite everyone who attended Kubecon EU to add their comments :)

doc: https://docs.google.com/document/d/1EJnrSwPp-2fVnjow0WbGmyYvfyciQa9ocmKHA-TQ3yc/edit#

**Comment by leonardpahlke** [comment]
I have added the following structure to the blog post:

1. general information about the TAG and environmental sustainability related things at the conference
   1. Introducing CNCF Environmental Sustainability Technical Advisory Group (TAG)
   2. Environmental Sustainability related talk and meetups at KubeCon / CloudNativeCon EU 2023
2. interview style sections 
   1. What we are excited to see at KubeCon / CloudNativeCon EU 2023
   2. What we are looking forward to collaborating on in the upcoming months
   3. Interesting discussions we had at KubeCon / CloudNativeCon EU 2023

The interview style sections have the following structure:

[Person A] answer

[Person B] answer

...

WDYT about the blog post structure?

**Comment by leonardpahlke** [comment]
I have created a google form to collect responses: https://docs.google.com/forms/d/1tIttAyrvWTWNq0UwCcufUGSXLh5oKP8z7BGS50_vPn8/edit

**Comment by caradelia** [comment]
@leonardpahlke maybe it is user error but am not having luck in answering the way the Google Form is currently set up. It will not allow to answer in the Short or Long paragraph area. Do you mind looking at?

**Comment by leonardpahlke** [comment]
this is the link to submit: https://docs.google.com/forms/d/e/1FAIpQLScQ_Tkrb0GjnHuze8qoV-fR1N77F1o-Gt8SBKPOXFTsTVqU9Q/viewform?usp=sf_link

**Comment by leonardpahlke** [comment]
> I have created a google form to collect responses: https://docs.google.com/forms/d/1tIttAyrvWTWNq0UwCcufUGSXLh5oKP8z7BGS50_vPn8/edit
the above is for editing the form :D

**Comment by leonardpahlke** [comment]
@nikimanoledaki already filled it out, thanks! :)

**Comment by guidemetothemoon** [comment]
Regarding the blog post: the structure is great and awesome work on the blog post so far! 💪
I added a few suggestions as well as updated YouTube links for the listed session recordings.
I can help writing an abstract of the conclusion section once the responses from surveys will be included, but if there's anything more I can contribute with other places in the blog post, just tag me 😊

**Comment by leonardpahlke** [comment]
I have updated the blog post with the comments by  @eduardoriveror, @guidemetothemoon, @nikimanoledaki, @david-m-m, @AntonioDiTuri

please take a look (you can still modify your comment 😉)

➡️ https://docs.google.com/document/d/1EJnrSwPp-2fVnjow0WbGmyYvfyciQa9ocmKHA-TQ3yc/edit#

**Comment by nikimanoledaki** [comment]
Thank you for putting it together @leonardpahlke @guidemetothemoon, it's great! 💚

@catblade and I have added some suggestions in the doc.

I also went ahead and made some direct changes and wrote a part of the summary/conclusion - please feel free to edit, leave feedback, or add more! :)

**Comment by guidemetothemoon** [comment]
Fantastic effort, thanks @catblade and @nikimanoledaki for additional updates to the blog post! I absolutely love how the KubeCon + CloudNativeCon sessions were grouped by the domain, with a small summary provided for each session. Section on our reflections from the conference is also very good and resonates with me a lot. I took the courtesy to make minor adjustments and improvements to the content here and there, but all in all I love how the blog post is turning out to be!

Don't hesitate to add any other improvements that you see fit or tag me if there's anything I should follow up further or take a look at 😊

Looking forward to it's official release to the public!

**Comment by leonardpahlke** [comment]
Awesome, thanks! I have opened a PR to publish the blog. https://github.com/cncf/tag-env-sustainability/pull/109

I can add your suggestions to it later.

**Comment by leonardpahlke** [comment]
Its published: https://tag-env-sustainability.cncf.io/blog/2023-wrap-up-kccn-eu/
