### ISSUE TITLE
[Tracking - Retro] TAG ENV presence at Kubecon EU

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#86]
This tracking issue is a used to collect async retro items from anyone attended Kubecon EU.

Please use the following template:
```
* **KEEP DOING**:
* **MORE OF**:
* **START DOING**: 
* **STOP DOING**:
* **LESS OF**: 
* **IDEAS**:
```

We will discuss anything added to the issue in an upcoming TAG Meeting.

**Comment by leonardpahlke** [comment]
ad-hoc my thoughts
* **KEEP DOING**: meetup's, talks, any ambassador things at conferences
* **MORE OF**: informal meetup's
* **START DOING**: announcements in slack and SM about whats happening each day at the conference
* **STOP DOING**: 
* **LESS OF**: avoid discussions which are clearly not about TAG topics during TAG meetup times
* **IDEAS**: TAG ENV kiosk (mini booth) next conference, sustainability track at conferences

**Comment by nikimanoledaki** [comment]
* **KEEP DOING**: 
  * talks lists, keynotes, informal and formal meetings, shoutouts ❤️
* **MORE OF**: 
  * marketing through social media e.g. LinkedIn, Twitter (it's not great but it can help with advocacy and reach)
  * I wish we had taken a group photo!
* **START DOING**:
  * Increase collaboration with the Green Software Foundation - for example, we could invite some folks to join as GSF ambassadors.
  * Try to get folks from the cloud hyperscalers to join the TAG. For example, Microsoft has a fleet of green cloud advocates.
  *  "Getting Started" guide for newcomers to the TAG. This could contain a list of things to read (e.g. the whitepaper), as well as some easy tasks to pick up - maybe we could ad some "good first issues"?
* **STOP DOING**: 
* **LESS OF**: 
* **IDEAS**: 

re: @leonardpahlke's thoughts:
+ 1 mini booth for TAG ENV ! I believe TAG App Delivery had one?
+1 sustainability track

**Comment by leonardpahlke** [comment]
cc @mkorbi @caradelia @by-d-sign @kristina-devochko @fredmenez and anyone else :)

**Comment by kristina-devochko** [comment]
Tagging my primary GitHub account to follow-up: @guidemetothemoon

**Comment by leonardpahlke** [comment]
@mkorbi @caradelia @by-d-sign @guidemetothemoon if you have a minute could you share your feedback about the TAG ENV presence at KCCN EU? Thanks!

**Comment by guidemetothemoon** [comment]
This issue can probably be closed or shall we aggregate this feedback somewhere first?
