### ISSUE TITLE
[Action] Getting started with the TAG ENV meeting, Post Kubecon

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#87]
This issue is about scheduling another meeting (post Kubecon, one time) for folks interested in the TAG ENV.

After Kubecon the TAG raised awareness and we expect to see a few new faces which would benefit from a dedicated separately getting started meeting. 

For the organization of the meeting (slides, agenda, communication, ...) we need a main organizer (co-chair / TL) and anyone who wants to support us.
* **Host**: @leonardpahlke 
* **Supporting Host**: @guidemetothemoon

**Comment by leonardpahlke** [comment]
We encourage anyone attending the getting started meeting to comment on this blog post issue https://github.com/cncf/tag-env-sustainability/issues/85 as this is a great opportunity for making the first contribution to the TAG!

**Comment by leonardpahlke** [comment]
ideally we would like to host the meeting early May (as soon as possible)

**Comment by ADiTuri** [comment]
Hi! I was at Kubekon and I had the pleasure to meet some of you guys in person. I am amazed by your work so far and I am looking foreword to help you! Do you have a get-started guide for new joiners? If not I would love to contribute to the first one.

**Comment by leonardpahlke** [comment]
Hey @ADiTuri 👋 , awesome that you reach out! Yes, we do have some documentation about how to get started (see [CONTRIBUTING.md](https://github.com/cncf/tag-env-sustainability/blob/main/CONTRIBUTING.md)). We are actually in the process of getting this more sharp! If you like you can open a PR and improve on that, this would help a ton!

Here are a few other links which I usually reference to get started:

* kubernetes.dev/docs/guide
* contribute.cncf.io
* I have actually also wrote a blog some time ago about it: lvsp.io/posts/start-contributing-to-open-source

I general, its good to do exactly what you did right now by looking up the repo, checking the issues and commenting on the first which sounds interesting to you! Join our meetings. We also plan to organize a getting started meeting soon (probably 10th of May)

**Comment by leonardpahlke** [comment]
Meeting schedule for the 10th of May.

**Comment by AntonioDiTuri** [comment]
Unfortunately I will not be able to join on may 10th cause I will be on holiday till the 22nd. It seems I have a lot to read anyway :) as soon as I will be back I will take part in the meetings and I will try to improve the guide if necessary! Thanks for your warm welcome and hope to work together soon!

**Comment by guidemetothemoon** [comment]
Not sure how experienced the co-host should be but I will be joining the meeting and I will be happy to help out with hosting, notes or anything else that may be needed for this meeting :)

**Comment by leonardpahlke** [comment]
Awesome! Thanks

**Comment by leonardpahlke** [comment]
The meeting went great yesterday! If you havent been able to attend the meeting you can follow up on the [meeting notes](https://docs.google.com/document/d/1TkmMyXJABC66NfYmivnh7z8Y_vpq9f9foaOuDVQS_Lo/edit#) and checkout out the slides (see [slack](https://cloud-native.slack.com/archives/C03F270PDU6/p1683734538819809?thread_ts=1683730297.228689&cid=C03F270PDU6)). Thanks @guidemetothemoon for taking notes!

We will organize another *Getting Started with TAG ENV* likely end of September (after [OSS EU](https://events.linuxfoundation.org/open-source-summit-europe/))
