### ISSUE TITLE
[Action] Open source summit NA

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#88]
The [open source summit NA](https://events.linuxfoundation.org/open-source-summit-north-america/) is around the corner and starts early may in Vancouver. This is a big conference and relevant to the TAG! The conference has a sustainability track.

To guide anyone from the TAG who might be at the conference it would be great to add a page to the TAG website (like we did for kubecon EU: https://tag-env-sustainability.cncf.io/events/2023-kubecon-eu/)

folder: https://github.com/cncf/tag-env-sustainability/tree/main/website/content/events

**Comment by leonardpahlke** [comment]
cc @nikimanoledaki

**Comment by leonardpahlke** [comment]
cc @berryq460

**Comment by berryq460** [comment]
Yes saw this one and was just looking through the blog! Awesome work by the way! I can add a section about a meetup when the details are finalized

**Comment by leonardpahlke** [comment]
cc @caradelia

**Comment by leonardpahlke** [comment]
Thanks @caradelia https://github.com/cncf/tag-env-sustainability/pull/98
