### ISSUE TITLE
[Action] Upload TAG ENV meeting recordings

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#92]
The TAG ENV has a [youtube channel](https://www.youtube.com/channel/UCMOopJuyyIWB8vXGct1ffNw) to upload meetings to. At the moment we do not upload the meetings. It would be great find a volunteer to do this!
The meetings are uploaded automatically to zoom.

**Comment by catblade** [comment]
This one, te just log into the account and pull the cloud link and send to youtube.  How do we get to the youtube channel?  Do you already have that info?

Should probably do all meetings to date, while at it.

**Comment by leonardpahlke** [comment]
> How do we get to the youtube channel?

We received an email invitation from Amye a few months ago. The TAG co-chairs should have access.

> Should probably do all meetings to date, while at it.

👍

**Comment by leonardpahlke** [comment]
FYI @amye, thoughts?

**Comment by leonardpahlke** [comment]
Thanks @AntonioDiTuri ! @catblade before sharing, lets quickly sync on sharing passwords etc regarding the YT channel + Zoom with @amye here

**Comment by guidemetothemoon** [comment]
If you need backup, don't hesitate to reach out, I'll be happy to help out :)

**Comment by leonardpahlke** [comment]
Starting with the next session, we could livestream it on YT and thus automatically upload the recording. I would suggest that we try this at the next session.

**Comment by nikimanoledaki** [comment]
As an alternative, the GitOps WG uses Zapier to upload zoom recordings to youtube: https://zapier.com/apps/youtube/integrations/zoom/706921/upload-new-zoom-recordings-in-youtube
